### ISSUE TITLE
Errors out in the middle of training--unclear why?

### ISSUE THREAD

**Issue by austinreiter** [rbgirshick/py-faster-rcnn#126]
Hi,

I got faster-rcnn to train on my custom dataset and things seemed to be going fine.  I got to about 25,000 iterations and even 2 snapshots saved out.  Then all of a sudden on iteration 25,700 I get the following error.  Anybody else see this or know why it happens?  

I0324 11:34:35.782372 28430 sgd_solver.cpp:106] Iteration 25700, lr = 0.001
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/austin/dev/ThirdParty/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/austin/dev/ThirdParty/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)
  File "/home/austin/dev/ThirdParty/py-faster-rcnn/tools/../lib/rpn/anchor_target_layer.py", line 137, in forward
    gt_argmax_overlaps = overlaps.argmax(axis=0)
ValueError: attempt to get argmax of an empty sequence

**Comment by happyharrycn** [comment]
My guess is that you have an image without a ground truth bounding box, such that overlaps is an empty array. The issue should have been solved with a recent commit, where filter_roidb function is applied before training to throw away "background" images.

**Comment by LiberiFatali** [comment]
Any suggestions to fix this?

**Comment by ch237** [comment]
I have the same error too. I have tried to remove the images with ROI width and height ratio being too small or too large. Still got this error.

**Comment by jmiller656** [comment]
I was having the same problem. After paying close attention to the iteration that the error occurred on, I noticed I always got an error at iteration 2290 with my dataset. After removing the 2290th image from my training set, the error stopped occurring (the image was somewhat large-ish 1280x720). Hope this helps!

**Comment by ArturoDeza** [comment]
All my images are 1024 x 760, and I've been having a similar error (all my bounding boxes are also small, (about 50x50), and in some cases there is no bounding box, since there is no person in the image. Does this mean that I can't do anything about it with the traditional R-CNN?

**Comment by hanjf12** [comment]
@austinreiter @ch237 I met the same error，do you have solved it?

**Comment by chakpongchung** [comment]
@jmiller656 How do you know which is the 2290th image(s) in your training sets?

**Comment by nmahesh01** [comment]
@hanjf12 @chakpongchung Did you solve this error? I am training the network on VOC2007 + VOC 2012 
@jmiller656 : was it the 2990th image in 'trainval.txt' ? Was your batch size set to 1?

**Comment by jmiller656** [comment]
@nmahesh01 Hey, sorry for the very confusing comment. I did actually end up facing this issue again later. I believe the problem ended up being images in the dataset with no bounding box. The 2990th image from my dataset ended up being one of those
