### ISSUE TITLE
[IndexError: Index out of range] While I training on ImageNet dataset.

### ISSUE THREAD

**Issue by JudeLee19** [rbgirshick/py-faster-rcnn#160]
I tried to train ImageNet dataset with pre-trained VGG16 model which provided by ImageNet model (solver.prototxt, VGG16.v2.caffemodel) following this post http://sunshineatnoon.github.io/Train-fast-rcnn-model-on-imagenet-without-matlab/

I created imagenet.py file in $FRCNN_ROOT/lib/datasets directory and follow all of the steps.  But when I tried I got below error messages.
==============================================================================
I0427 13:33:15.288508  8314 layer_factory.hpp:77] Creating layer input-data
I0427 13:33:15.307318  8314 net.cpp:106] Creating Layer input-data
I0427 13:33:15.307342  8314 net.cpp:411] input-data -> data
I0427 13:33:15.307358  8314 net.cpp:411] input-data -> im_info
I0427 13:33:15.307368  8314 net.cpp:411] input-data -> gt_boxes
Top length : 3
XX: 3 <class 'caffe._caffe.RawBlobVec'> ['__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__hash__', '__init__', '__instance_size__', '__iter__', '__len__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'append', 'extend']
Error idx is 3
Traceback (most recent call last):
  File "./tools/train_net.py", line 113, in <module>
    max_iters=args.max_iters)
  File "/home/dev/bcached/opensource/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 134, in train_net
    pretrained_model=pretrained_model)
  File "/home/dev/bcached/opensource/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 43, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
  File "/home/dev/bcached/opensource/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 128, in setup
    top[idx].reshape(1, self._num_classes * 4)
IndexError: Index out of range
==============================================================================

Thank you in advance.

**Comment by loveorchids** [comment]
I have the same problem, did u solved that?

**Comment by Leonardyao** [comment]
Changing cfg.TRAIN.HAS_RPN to be True. Maybe some debugging could help...

**Comment by stanley-king** [comment]
it is not config bug.it is muliti process data share bug.
    
# cfg.TRAIN.SNAPSHOT_INFIX = 'stage1'
    # mp_kwargs = dict(
    #         queue=mp_queue,
    #         imdb_name=args.imdb_name,
    #         init_model=args.pretrained_model,
    #         solver=solvers[0],
    #         max_iters=max_iters[0],
    #         cfg=cfg)
    # p = mp.Process(target=train_rpn, kwargs=mp_kwargs)
    # p.start()
    # rpn_stage1_out = mp_queue.get()
    # p.join()

    cfg.TRAIN.SNAPSHOT_INFIX = 'stage1'
    train_rpn(queue=mp_queue,
            imdb_name=args.imdb_name,
            init_model=args.pretrained_model,
            solver=solvers[0],
            max_iters=max_iters[0],
            cfg=cfg)
    rpn_stage1_out = mp_queue.get()
