### ISSUE TITLE
The .so file cannot import "failed to map segment from shared object"

### ISSUE THREAD

**Issue by Paralysis** [rbgirshick/py-faster-rcnn#162]
Hi, I followed the protocol provided and when I run 'python tools/demo.py' I got this problem. I am using anaconda python on ubuntu 14.04. Could somebody kindly tell me how to deal with this problem? 

Traceback (most recent call last):
  File "tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/media/research/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/media/research/py-faster-rcnn/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: /media/research/py-faster-rcnn/tools/../lib/nms/gpu_nms.so: failed to map segment from shared object

**Comment by wuzheng-sjtu** [comment]
hi, @Paralysis have you solved the problem? Seems like we have similar problem.

**Comment by MartinPlantinga** [comment]
The reason you are getting that message is probably that the partition you have mounted, i.e. /media/research/ does not have executable permission. Remount the partition with executable permission as explained in: https://askubuntu.com/questions/311438/how-to-make-tmp-executable.

If you mount the drive with fstab, see: https://askubuntu.com/questions/678857/fstab-doesnt-mount-with-exec.
