### ISSUE TITLE
How to finetune pascal voc 2007 model with my images?

### ISSUE THREAD

**Issue by limorbagizada** [rbgirshick/py-faster-rcnn#166]
How to finetune pascal voc 2007 model with my images?
I am new with deep learning and faster rcnn.
I have a folder of my images and I want to finetune it with the pascal voc 2007 model. How to do this?
Thanks

**Comment by deboc** [comment]
Hi,
There was already issues opened for fine-tuning the network on your own dataset.
If it can help I have made [a tutorial](https://github.com/deboc/py-faster-rcnn/blob/master/help/Readme.md) on fine tuning py-faster-rcnn for a binary classifier.

But you should start with the [caffe official website](http://caffe.berkeleyvision.org) if you are totally new with caffe.

**Comment by ericromanenghi** [comment]
Close the issue please, there si a lot of issues in the repo about this.

**Comment by guysoft** [comment]
I suggest you close it *only* if you link a duplicate issue. then you get all of the issues pointing to one.

**Comment by useebear** [comment]
@deboc 
Hello Deboc, I followed your tutorial and did change all 84 to 8, but still came across such error during training as following. Thanks.

0923 16:21:49.104301  6578 sgd_solver.cpp:106] Iteration 9980, lr = 0.001
speed: 0.107s / iter
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 195, in train_fast_rcnn
    max_iters=max_iters)
  File "/home/surview/Test/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/surview/Test/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 108, in train_model
    model_paths.append(self.snapshot())
  File "/home/surview/Test/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 73, in snapshot
    self.bbox_stds[:, np.newaxis])
ValueError: operands could not be broadcast together with shapes (84,1024) (8,1)

**Comment by deboc** [comment]
Hi,
I think it's a [cache issue](https://github.com/rbgirshick/py-faster-rcnn/issues/31#issuecomment-223743326) with your former batches.

**Comment by nassarofficial** [comment]
@useebear did @deboc reply solve your problem, because my cache is empty, and Im still getting this error!

**Comment by useebear** [comment]
@nassarofficial, thanks for the advice of @deboc. I have found the problem. It is because the prototxt is not in the correct folder. Check the folder.

**Comment by mohamed-ezz** [comment]
I had the same problem as @useebear , turned out I forgot to adjust the paths in the _solver.pt files. They have a path relative to the repo root dir so they point to `models/pascal_voc/...` by default.
