### ISSUE TITLE
Training on ImageNet met an error in minibatch.py of roi_data_layer

### ISSUE THREAD

**Issue by Jianchao-ICT** [rbgirshick/py-faster-rcnn#17]
Hi all, I am now training the py-faster-rcnn on ImageNet detections data. I create an `ilsvrc.py` in `./lib/datasets` for the ImageNet dataset and modified related codes. My training goes smoothly in the *Stage 1 RPN Training* and *Stage 1 Generate RPN Porposals*. But in *Stage 1 Fast RCNN Training using RPN Proposals*, I came across the following error. I check the related codes but still have no idea of what is wrong.

 Could anyone gives me some suggestions? Thanks!

	Traceback (most recent call last):
	  File "/home/code/lijianchao/anaconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
		self.run()
	  File "/home/code/lijianchao/anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run
		self._target(*self._args, **self._kwargs)
	  File "./tools/train_faster_rcnn_alt_opt.py", line 196, in train_fast_rcnn
		max_iters=max_iters)
	  File "/home/code/lijianchao/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 138, in train_net
		model_paths = sw.train_model(max_iters)
	  File "/home/code/lijianchao/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 104, in train_model
		self.solver.step(1)
	  File "/home/code/lijianchao/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 143, in forward
		blobs = self._get_next_minibatch()
	  File "/home/code/lijianchao/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 62, in _get_next_minibatch
		return get_minibatch(minibatch_db, self._num_classes)
	  File "/home/code/lijianchao/py-faster-rcnn/tools/../lib/roi_data_layer/minibatch.py", line 55, in get_minibatch
		num_classes)
	  File "/home/code/lijianchao/py-faster-rcnn/tools/../lib/roi_data_layer/minibatch.py", line 125, in _sample_rois
		roidb['bbox_targets'][keep_inds, :], num_classes)
	  File "/home/code/lijianchao/py-faster-rcnn/tools/../lib/roi_data_layer/minibatch.py", line 176, in _get_bbox_regression_labels
		bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
	ValueError: could not broadcast input array from shape (4) into shape (0)

**Comment by agatabcool** [comment]
I know this is closed, but do you happen to remember how you solved this?

**Comment by harora** [comment]
Even i am facing the same issue , Can someone help on this?

**Comment by agatabcool** [comment]
For me this ended up being a really silly mistake- my solver prototxt was pointing to the wrong train prototxt- that is the one with the incorrect number of classes/outputs
