### ISSUE TITLE
protobuf module has no attribute 'text_format'

### ISSUE THREAD

**Issue by kepricon** [rbgirshick/py-faster-rcnn#198]
Hi all

Before i get into reporting my problem, I really appreciate sharing this valuable project.

When i train faster r-cnn using pascal dataset, i faced some error like below (end of this report).
I executed "./experiments/scripts/faster_rcnn_end2end.sh 0 VGG_CNN_M_1024 pascal_voc" at  ROOT DIR of py-faster-rcnn.
It shows me like below.
  File "/home/kepricon/git/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 51, in __init__
    pb2.text_format.Merge(f.read(), self.solver_param)
AttributeError: 'module' object has no attribute 'text_format'

I tried to change the version of protobuf using pip. However it didn't work for me.

Is anybody have a idea for this?

please let me know.

Best Regards,
DH

-detailed error messages (part of the log)
I0520 17:36:12.559183 24964 net.cpp:228] norm1 does not need backward computation.
I0520 17:36:12.559187 24964 net.cpp:228] relu1 does not need backward computation.
I0520 17:36:12.559190 24964 net.cpp:228] conv1 does not need backward computation.
I0520 17:36:12.559195 24964 net.cpp:228] gt_boxes_input-data_2_split does not need backward computation.
I0520 17:36:12.559200 24964 net.cpp:228] im_info_input-data_1_split does not need backward computation.
I0520 17:36:12.559203 24964 net.cpp:228] data_input-data_0_split does not need backward computation.
I0520 17:36:12.559207 24964 net.cpp:228] input-data does not need backward computation.
I0520 17:36:12.559211 24964 net.cpp:270] This network produces output loss_bbox
I0520 17:36:12.559214 24964 net.cpp:270] This network produces output loss_cls
I0520 17:36:12.559218 24964 net.cpp:270] This network produces output rpn_cls_loss
I0520 17:36:12.559221 24964 net.cpp:270] This network produces output rpn_loss_bbox
I0520 17:36:12.559250 24964 net.cpp:283] Network initialization done.
I0520 17:36:12.559466 24964 solver.cpp:60] Solver scaffolding done.
Loading pretrained model weights from data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel
I0520 17:36:13.513700 24964 net.cpp:816] Ignoring source layer pool5
I0520 17:36:13.560518 24964 net.cpp:816] Ignoring source layer fc8
I0520 17:36:13.560544 24964 net.cpp:816] Ignoring source layer prob
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/kepricon/git/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 157, in train_net
    pretrained_model=pretrained_model)
  File "/home/kepricon/git/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 51, in __init__
    pb2.text_format.Merge(f.read(), self.solver_param)
AttributeError: 'module' object has no attribute 'text_format'

**Comment by lemonsakura** [comment]
same problem,have you solved?

**Comment by lemonsakura** [comment]
solved by adding  import google.protobuf.text_format

**Comment by bybabo92** [comment]
i have same problem as lemonsakura.  as his method i have solved
adding "import google.protobuf.text_format" in the train.py

**Comment by zhengziqiang** [comment]
have you solved this problem?

**Comment by bybabo92** [comment]
我是中国的，直接说中文吧，解决方法和上面说的一样貌似是一个模块没有声明，直接加一句话在train.py开头就行

**Comment by xxbabybearss** [comment]
请问如何在Mac上配置运行py-faster-rcnn呀？有谁可以解答一下吗？拜托了！

**Comment by xxbabybearss** [comment]
I am eager to learn how to run the py-faster-rcnn on my Mac.Could anyone who knows it please help me?Thanks a lot!

**Comment by Derekabc** [comment]
hi,
    where can i find the train.py?

**Comment by liu09114** [comment]
$py-faster-rcnn/tools

**Comment by Derekabc** [comment]
Thanks , I have find it .

**Comment by Derekabc** [comment]
hi I am also a UESTC

**Comment by hackershi** [comment]
after I installed tensor flow, this bug emerges. solved it by adding import google.protobuf.text_format
