### ISSUE TITLE
Floating point exception (core dumped) when running demo.py

### ISSUE THREAD

**Issue by mux42** [rbgirshick/py-faster-rcnn#265]
Running demo.py --cpu (using a CPU-only compiled caffe) yields the following lines:

Loaded network /home/labuser/py-faster-rcnn/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel
Floating point exception (core dumped)

How can I fix this?

Prior to this, I had to change line 154 in /lib/rpn/proposal_layer.py from:

`if post_nms_topN > 0:
             keep = keep[:post_nms_topN]
`
to:
`if post_nms_topN > 0:
            if keep is None:
                keep = []
            else:
               keep = keep[:post_nms_topN]
`
to solve the previous run-time error:

Traceback (most recent call last):
  File "tools/demo.py", line 142, in <module>
    _, _= im_detect(net, im)
  File "/home/labuser/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 154, in im_detect
    blobs_out = net.forward(**forward_kwargs)
  File "/home/labuser/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 105, in _Net_forward
    self._forward(start_ind, end_ind)
  File "/home/labuser/py-faster-rcnn/tools/../lib/rpn/proposal_layer.py", line 146, in forward
    keep = keep[:post_nms_topN]
TypeError: 'NoneType' object has no attribute '__getitem__'

There seems to be a problem with variable keep being None. Anyone had the same problem before? Thanks

**Comment by IamMegatron2025** [comment]
＠dkonomis　＠dicksonchin I have the same error. Have you solved this?
