### ISSUE TITLE
raise Exception('Input blob arguments do not match net inputs.')

### ISSUE THREAD

**Issue by wangjunfeng90214** [rbgirshick/py-faster-rcnn#289]
When I run the python faster rcnn using this command:
./experiments/scripts/faster_rcnn_alt_opt.sh 1 ZF pascal_voc --set EXP_DIR seed_rng1701 RNG_SEED 1701

I have met this problem:
net is : 
<caffe._caffe.Net object at 0x7f224ef078e8>
imdb is: 
<datasets.pascal_voc.pascal_voc object at 0x7f224ef02890>
voc_2007_test ss roidb loaded from /home/wangjunfeng/py-faster-rcnn/data/cache/voc_2007_test_selective_search_roidb.pkl
kwargs: 
['rois', 'data']
self.inputs: 
['data', 'im_info']
Traceback (most recent call last):
  File "./tools/test_net.py", line 98, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "/home/wangjunfeng/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 258, in test_net
    scores, boxes = im_detect(net, im, box_proposals)
  File "/home/wangjunfeng/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 154, in im_detect
    blobs_out = net.forward(**forward_kwargs)
  File "/home/wangjunfeng/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 103, in _Net_forward
    raise Exception('Input blob arguments do not match net inputs.')
The line numbers may be different as I added some print lines.

How to solve this issue?

**Comment by tommgalati** [comment]
Hi, wangjunfeng90214
I have the same problem. Did you solve this issue?

**Comment by fahaihappy** [comment]
I set __C.TEST.HAS_RPN = True in lib/fast_rcnn/config.py, and in runs Ok
