### ISSUE TITLE
Error Training on 4 classes

### ISSUE THREAD

**Issue by Sai-Manikantha** [rbgirshick/py-faster-rcnn#316]
Hi all,
I am trying to train py-faster-rcnn network on PASCAL VOC 2007 dataset on 4 classes. I have changed the classes variable in pascal_voc.py and I have also made proper changes in train and test prototxt files. But I am getting the following error while training. Did anyone encounter a similar problem? Any help would be appreciated.

Log is as below:

Number of classes : 4
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
objs :  [<Element 'object' at 0x7fe2660a85d0>, <Element 'object' at 0x7fe2660a8850>, <Element 'object' at 0x7fe2660a8d50>]
Traceback (most recent call last):
  File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/sai/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 118, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/sai/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 106, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/sai/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "/home/sai/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 111, in gt_roidb
    for index in self.image_index]
  File "/home/sai/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 217, in _load_pascal_annotation
    cls = self._class_to_ind[obj.find('name').text.lower().strip()]
KeyError: 'chair'

**Comment by karaspd** [comment]
You probably need to write some line of codes to ignore any objects with classes except the classes you are looking for when you are loading the annotation _load_pascal_annotation.
Something like 
cls_objs = [
                obj for obj, clas in objs, self._classes if obj.find('name').text== clas]

**Comment by jhsonn** [comment]
@Sai-Manikantha  Did you solve your error?
Hi, I'm also trying to train only 5 classes in PASCAL VOC 2007 dataset. Exactly same error occured here. Can anybody please give me a advice? I modified /lib/datasets/pascal_voc.py and proper prototext files. Both faster_rcnn_alt_opt and faster_rcnn_end2end produce same error. 

Modifications I made is below:
/lib/datasets/pascal_voc.py , line 31)
self._classes = ('__background__', # always index 0
                          bicycle', 'cat', 'dog', 'person')

(in case of using faster_rcnn_end2end and ZF network) 
/models/pascal_voc/ZF/faster_rcnn_end2end/train.prototxt
num_classes in "input-data" : 21 to 5
num_output in "cls_score" : 21 to 5
num_output in "bbox_pred" : 84 to 20
(same modification applied to test.prototxt)

Command I used : "./experiments/scripts/faster_rcnn_end2end.sh 0 ZF pascal_voc"
Log is below: 
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=0
+ NET=ZF
+ NET_lc=zf
+ DATASET=pascal_voc
+ array=($@)
+ len=3
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case $DATASET in
+ TRAIN_IMDB=voc_2007_trainval
+ TEST_IMDB=voc_2007_test
+ PT_DIR=pascal_voc
+ ITERS=70000
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/faster_rcnn_end2end_ZF_.txt.2016-09-11_22-05-39
+ exec
++ tee -a experiments/logs/faster_rcnn_end2end_ZF_.txt.2016-09-11_22-05-39
+ echo Logging output to experiments/logs/faster_rcnn_end2end_ZF_.txt.2016-09-11_22-05-39
Logging output to experiments/logs/faster_rcnn_end2end_ZF_.txt.2016-09-11_22-05-39
+ ./tools/train_net.py --gpu 0 --solver models/pascal_voc/ZF/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/ZF.v2.caffemodel --imdb voc_2007_trainval --iters 70000 --cfg experiments/cfgs/faster_rcnn_end2end.yml
Called with args:
Namespace(cfg_file='experiments/cfgs/faster_rcnn_end2end.yml', gpu_id=0, imdb_name='voc_2007_trainval', max_iters=70000, pretrained_model='data/imagenet_models/ZF.v2.caffemodel', randomize=False, set_cfgs=None, solver='models/pascal_voc/ZF/faster_rcnn_end2end/solver.prototxt')
Using config:
{'DATA_DIR': '/home/hope/jhson/caffe/py-faster-rcnn2/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/hope/jhson/caffe/py-faster-rcnn2/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/hope/jhson/caffe/py-faster-rcnn2',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
Traceback (most recent call last):
  File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/fast_rcnn/train.py", line 118, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/datasets/imdb.py", line 106, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/datasets/pascal_voc.py", line 103, in gt_roidb
    for index in self.image_index]
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/datasets/pascal_voc.py", line 208, in _load_pascal_annotation
    cls = self._class_to_ind[obj.find('name').text.lower().strip()]
KeyError: 'chair'

Stuck this error more than a week.. Any kind of help would be appreciated. Thanks!

**Comment by Sai-Manikantha** [comment]
@karaspd I'm sorry for the late reply. Thank you so much for your help. I added some code as you suggested. Now I am able to train PASCAL VOC dataset on 4 classes.

**Comment by Sai-Manikantha** [comment]
@jhsonn Hi !! You can follow the steps suggested by @karaspd. Please feel free to post if it doesn't work for you.
```
    cls_objs = [obj for obj, clas in objs, self._classes if obj.find('name').text== clas]
    objs = cls_objs
```

**Comment by jhsonn** [comment]
@Sai-Manikantha Hi, I modified pascal_voc.py as you posted but it still doesn't work..

 File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/fast_rcnn/train.py", line 118, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/datasets/imdb.py", line 106, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/datasets/pascal_voc.py", line 103, in gt_roidb
    for index in self.image_index]
  File "/home/hope/jhson/caffe/py-faster-rcnn2/tools/../lib/datasets/pascal_voc.py", line 184, in _load_pascal_annotation
    cls_objs = [obj for obj, clas in objs, self._classes if obj.find('name').text== clas]
ValueError: too many values to unpack

Above is my error message. Can you tell me more detail about modification you made? (like which line of code you modified and how) I'm not sure where to put "cls_objs=[obj for....]" and what to delete. Thanks in advance! I really hope someday I can train this model without any error..

**Comment by Sai-Manikantha** [comment]
Hi @jhsonn, when you are loading the annotation in _load_pascal_annotation method, look for something like 
`objs = diff_objs (or non_diff_objs)`
After that line insert something similar to below code
```
cls_objs = [obj for obj in objs if obj.find('name').text in self._classes]
objs = cls_objs
```
Hope this helps.

**Comment by jhsonn** [comment]
@Sai-Manikantha Thank you so much for your help! I've done training without any error. Thanks again.

**Comment by Po-Hsuan-Huang** [comment]
@jhsonn 

I think your first problem is that you forgot to delete the plk file in  /data/cache folder. The program reads the already generated data table from cache to increase speed. That is the only reason I can think of why you get a class that is not in self._classes.

@karaspd 

`cls_objs = [obj for obj in objs if obj.find('name').text in self._classes]
objs = cls_objs
`
Only returns cls_objs in self._classes. What causes ojbs get classes not defined in self._classes ?

Thanks

**Comment by pasonx** [comment]
@jhsonn Hi friend, can you tell me how do you debug your error? thanks so much

**Comment by zhilaAI** [comment]
`Hi` guys
I have the same problem but for test data set. Can anybody help me how to solve it?

`VOC07 metric? Yes
Traceback (most recent call last):
  File "./tools/test_net.py", line 120, in <module>
    test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
  File "/home/zhila/Seal_detection/tf-faster-rcnn/tools/../lib/model/test.py", line 192, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/zhila/Seal_detection/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 279, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/zhila/Seal_detection/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 242, in _do_python_eval
    use_07_metric=use_07_metric, use_diff=self.config['use_diff'])
  File "/home/zhila/Seal_detection/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 137, in voc_eval
    R = [obj for obj in recs[imagename] if obj['name'] == classname]
KeyError: '0802_100_Seal__PB_003'
Command exited with non-zero status 1
48.71user 10.26system 1:15.89elapsed 77%CPU (0avgtext+0avgdata 3046436maxresident)k
99264inputs+3376outputs (0major+715410minor)pagefaults 0swaps`

**Comment by shirleyatgithub** [comment]
@zhilaAI Hi, I have encountered the same error as yours. Have you solved this problem? could you tell me how to ?
