### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by khaledbay** [rbgirshick/py-faster-rcnn#336]
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "/media/sage/3a621a44-a12e-4444-9bf4-bef717055250/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 295, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/media/sage/3a621a44-a12e-4444-9bf4-bef717055250/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 322, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/media/sage/3a621a44-a12e-4444-9bf4-bef717055250/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 285, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/media/sage/3a621a44-a12e-4444-9bf4-bef717055250/py-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 148, in voc_eval
    BB = BB[sorted_ind, :]
IndexError: too many indices

**Comment by sbrugman** [comment]
I have the same problem on #338. Some files appear to be empty, producing this error.

**Comment by ubenz55555** [comment]
check your xml file ，some class might not be included，better check it one by one

**Comment by ubenz55555** [comment]
and also your trainset.txt、test.txt and train.txt ，check every item is included in these three files
