### ISSUE TITLE
AssetionError: training py-faster-rcnn with one class

### ISSUE THREAD

**Issue by yawadugyamfi** [rbgirshick/py-faster-rcnn#34]
I am using py-faster-rcnn to train the 2007 VOC dataset. When I run on the original 21 classes, it works fine, but when I change the original number of classes, I get an error.. 
I am doing this for 1 class ('person'). I made the following changes to the original codes:

1. file: fcn_root/models/VGG16/faster_rcnn_alt_opt.pt
        layer {
          name: "cls_score"
          type: "InnerProduct"
          bottom: "fc7"
          top: "cls_score"
          inner_product_param {
            num_output: 2
          }
}

    layer {
      name: "bbox_pred"
      type: "InnerProduct"
      bottom: "fc7"
      top: "bbox_pred"
      inner_product_param {
        num_output: 8
      }
    }

2. file2: fcn_root/lib/datasets/pascal_voc.py

    line 28:self._classes = ('__background__', # always index 0
                                 'person')
      
 # removed -1's from the lines below
           x1 = float(get_data_from_tag(obj, 'xmin'))
            y1 = float(get_data_from_tag(obj, 'ymin'))
            x2 = float(get_data_from_tag(obj, 'xmax')) 
            y2 = float(get_data_from_tag(obj, 'ymax'))

3. file3: ../VOCdevkit/VOCcode/VOCinit.m

VOCopts.classes={...
        'person'};

 I get the following error after I run this command, 
#### ./experiments/scripts/faster_rcnn_alt_opt.sh 3 VGG16 \ --set EXP_DIR foobarx
I have also attached a full trace of my program running.
Error:
    Process Process-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "./tools/train_faster_rcnn_alt_opt.py", line 123, in train_rpn
        roidb, imdb = get_roidb(imdb_name)
      File "./tools/train_faster_rcnn_alt_opt.py", line 68, in get_roidb
        roidb = get_training_roidb(imdb)
      File "/home/microway/test/pytest/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 121, in       get_training_roidb
        imdb.append_flipped_images()
      File "/home/microway/test/pytest/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 108, in     append_flipped_images
        assert (boxes[:, 2] >= boxes[:, 0]).all()
    AssertionError

[error_attachment.txt](https://github.com/rbgirshick/py-faster-rcnn/files/52187/error_attachment.txt)

**Comment by marphil** [comment]
Hi,
I have also encountered this error. Seems like something is wrong in at least one of the annotations, an artificial solution is the following: in imdb.py

```python
for b in range(len(boxes)):     
                if boxes[b][2] < boxes[b][0]:
                   boxes[b][0] = 0

assert (boxes[:, 2] >= boxes[:, 0]).all()
```

Hope this helps!

**Comment by moyans** [comment]
@marphil  I get the following error:
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 122, in train_rpn
    roidb, imdb = get_roidb(imdb_name)
  File "./tools/train_faster_rcnn_alt_opt.py", line 67, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/media/dl/c0d34b51-8a78-4364-bc19-35003bf01885/RCNN/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 118, in get_training_roidb
    imdb.append_flipped_images()
  File "/media/dl/c0d34b51-8a78-4364-bc19-35003bf01885/RCNN/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 106, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/media/dl/c0d34b51-8a78-4364-bc19-35003bf01885/RCNN/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "/media/dl/c0d34b51-8a78-4364-bc19-35003bf01885/RCNN/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 103, in gt_roidb
    for index in self.image_index]
  File "/media/dl/c0d34b51-8a78-4364-bc19-35003bf01885/RCNN/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 204, in _load_pascal_annotation
    x1 = float(bbox.find('xmin').text)
ValueError: invalid literal for float(): 737,

**Comment by DiegoPortoJaccottet** [comment]
Hello yawadugyamfi, did you find a solution to your error? Would you share it with us please?

**Comment by attiliotnt** [comment]
@marphil  in which function you wrote those lines?

**Comment by attiliotnt** [comment]
@DiegoPortoJaccottet  I got sed: no input files

**Comment by alviur** [comment]
@marphil  that worked for me!

**Comment by CWOA** [comment]
@DiegoPortoJaccottet your fix worked for me, thanks! The @marphil fix produces the same assertion error in my case.

**Comment by harora** [comment]
@DiegoPortoJaccottet  Even i got sed : no input files. I have my annotation files in that folder ( *.xml)

**Comment by DiegoPortoJaccottet** [comment]
@harora 
You got 'sed: no input files' from the commands I described or from Faster-RCNN?

**Comment by Z0org** [comment]
@moyans i get the same error. Did you solve it?

**Comment by XiangyuChu** [comment]
@moyans  I get the same error with you. 

y2= float(bbox.find('ymax').text)
ValueError: invalid literal for float(): 196006001002176.jpg

Do you find any solution to it? Thank you

**Comment by moyans** [comment]
you need check this img and label. 


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Xiang <notifications@github.com>
时间：周五 5月5日 09:52
收件人：rbgirshick/py-faster-rcnn <py-faster-rcnn@noreply.github.com>
抄送：moyans <ice_moyan@163.com>,Mention <mention@noreply.github.com>
主题：Re: [rbgirshick/py-faster-rcnn] AssetionError: training py-faster-rcnn with one class (#34)

**Comment by XiangyuChu** [comment]
@moyans  196006001002176.jpg is very odd. My images are usually "000000.jpg", same as VOC2007. 
And I have removed "-1" from the lines below
     x1 = float(get_data_from_tag(obj, 'xmin'))
      y1 = float(get_data_from_tag(obj, 'ymin'))
      x2 = float(get_data_from_tag(obj, 'xmax')) 
      y2 = float(get_data_from_tag(obj, 'ymax'))

**Comment by moyans** [comment]
check the  label out of range?


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Xiang <notifications@github.com>
时间：周五 5月5日 10:32
收件人：rbgirshick/py-faster-rcnn <py-faster-rcnn@noreply.github.com>
抄送：moyans <ice_moyan@163.com>,Mention <mention@noreply.github.com>
主题：Re: [rbgirshick/py-faster-rcnn] AssetionError: training py-faster-rcnn with one class (#34)

**Comment by Designbook1** [comment]
in the Annotation folder I run 
`grep -rl '<ymin>0</ymin>' ./ | xargs sed -i 's#<ymin>0</ymin>#<ymin>1</ymin>#g'`
I got: `sed : no input files` just like @harora  . I want to know why. @DiegoPortoJaccottet

**Comment by XiangyuChu** [comment]
@moyans Thanks for your help. I have solved the error.  I found an error in "output.txt", i.e. 002175.jpg c 669 155 769 **196006001002176.jpg p 207 188 229 257.  What puzzles me is that I cannot find error in .xml. Anyway, it is solved. Thank you again!

**Comment by iamlxb3** [comment]
I replaced xmin 0 and ymin 0 with xmin 1 and ymin 1, all things resolved!

see more https://github.com/rbgirshick/py-faster-rcnn/issues/34

**Comment by ankitcsr** [comment]
> in the Annotation folder I run
> `grep -rl '<ymin>0</ymin>' ./ | xargs sed -i 's#<ymin>0</ymin>#<ymin>1</ymin>#g'`
> I got: `sed : no input files` just like @harora . I want to know why. @DiegoPortoJaccottet

replace 0 with 0.0
