### ISSUE TITLE
faster rcnn runs in windows and error occurs

### ISSUE THREAD

**Issue by wait1988** [rbgirshick/py-faster-rcnn#35]
Loaded network F:\sunqin\DeepLearning\Caffe\Projects\faster-rcnn\data\faster_rcnn_models\VGG16_faster_rcnn_final.caffemodel
I1207 10:04:07.956500 764992 python_layer.hpp:66] Traceback (most recent call last):
  File "F:\sunqin\DeepLearning\Caffe\Projects\faster-rcnn\tools\..\lib\rpn\proposal_layer.py", line 63, in forward
    cfg_key = str(self.phase) # either 'TRAIN' or 'TEST'
AttributeError: 'ProposalLayer' object has no attribute 'phase'
Traceback (most recent call last):
  File "./tools/demo.py", line 142, in <module>
    _, _= im_detect(net, im)
  File "F:\sunqin\DeepLearning\Caffe\Projects\faster-rcnn\tools\..\lib\fast_rcnn\test.py", line 155, in im_detect
    blobs_out = net.forward(**forward_kwargs)
  File "F:\sunqin\DeepLearning\Caffe\Projects\faster-rcnn\tools\..\caffe-fast-rcnn\python\caffe\pycaffe.py", line 95, in _Net_forward
    self._forward(start_ind, end_ind)
  File "F:\sunqin\DeepLearning\Caffe\Projects\faster-rcnn\tools\..\lib\rpn\proposal_layer.py", line 63, in forward
    cfg_key = str(self.phase) # either 'TRAIN' or 'TEST'
AttributeError: 'ProposalLayer' object has no attribute 'phase'

**Comment by wait1988** [comment]
I've fixed this error by defining a new field in cfg

**Comment by leejiajun** [comment]
@wait1988  How? 
Thank you

**Comment by wait1988** [comment]
@leejiajun
 First,you need to add a line in config:__C.PAHSE = 'TEST' (for test),and then replace "cfg_key = str(self.phase)" with "cfg_key =cfg.PAHSE" in proposal_layer.py.After these modifications,it should work.

**Comment by karaspd** [comment]
@wait1988 
I had the same issue and I've fixed it based on your modification. However, I have a question about it. If we fix the PAHSE to TEST wouldn't it effect the training?
Thank you
