### ISSUE TITLE
testing using resnet50 model

### ISSUE THREAD

**Issue by paul8666** [rbgirshick/py-faster-rcnn#353]
Hi, I tried to use VGG16_coco and everything is ok, but now I want to test resnet50 I have this error:

Loaded network /home/paul/adee/TerzoAnno/py-faster-rcnn/data/faster_rcnn_models/ResNet-50-model.caffemodel
Traceback (most recent call last):
  File "./tools/demo.py", line 172, in <module>
    _, _= im_detect(net, im)
  File "/home/paul/adee/TerzoAnno/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 144, in im_detect
    net.blobs['im_info'].reshape(*(blobs['im_info'].shape))
KeyError: 'im_info'

I downloaded resnet50 and ResNet-50-deploy.prototxt from the https://onedrive.live.com/?authkey=!AAFW2-FVoxeVRck&id=4006CBB8476FF777!17887&cid=4006CBB8476FF777

didi I make some mistake?
someone could solve this?

**Comment by fungtion** [comment]
I using vgg16 with coco, the same error

**Comment by youye115** [comment]
name: "ResNet-50"
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 224
  dim: 224
}
input: "im_info"
input_shape {
  dim: 1
  dim: 3
}

**Comment by lenhattu** [comment]
@fungtion Which part in the prototxt should I modify? I'm using another model (Mobilenet)

**Comment by Arthur-Shi** [comment]
@lenhattu Did you solve this problem?
