### ISSUE TITLE
AssertionError: Path does not exist: /home/mona/computer_vision/py-faster-rcnn/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt

### ISSUE THREAD

**Issue by monajalal** [rbgirshick/py-faster-rcnn#373]
How should I exactly feed the dataset in this command? `./experiments/scripts/faster_rcnn_end2end.sh 0 ZF pascal_voc` :

```
mona@pascal:~/computer_vision/py-faster-rcnn$ ./experiments/scripts/faster_rcnn_end2end.sh 0 ZF pascal_voc 
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=0
+ NET=ZF
+ NET_lc=zf
+ DATASET=pascal_voc
+ array=($@)
+ len=3
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case $DATASET in
+ TRAIN_IMDB=voc_2007_trainval
+ TEST_IMDB=voc_2007_test
+ PT_DIR=pascal_voc
+ ITERS=70000
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/faster_rcnn_end2end_ZF_.txt.2016-10-11_21-54-10
+ exec
++ tee -a experiments/logs/faster_rcnn_end2end_ZF_.txt.2016-10-11_21-54-10
+ echo Logging output to experiments/logs/faster_rcnn_end2end_ZF_.txt.2016-10-11_21-54-10
Logging output to experiments/logs/faster_rcnn_end2end_ZF_.txt.2016-10-11_21-54-10
+ ./tools/train_net.py --gpu 0 --solver models/pascal_voc/ZF/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/ZF.v2.caffemodel --imdb voc_2007_trainval --iters 70000 --cfg experiments/cfgs/faster_rcnn_end2end.yml
Called with args:
Namespace(cfg_file='experiments/cfgs/faster_rcnn_end2end.yml', gpu_id=0, imdb_name='voc_2007_trainval', max_iters=70000, pretrained_model='data/imagenet_models/ZF.v2.caffemodel', randomize=False, set_cfgs=None, solver='models/pascal_voc/ZF/faster_rcnn_end2end/solver.prototxt')
Using config:
{'DATA_DIR': '/home/mona/computer_vision/py-faster-rcnn/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/mona/computer_vision/py-faster-rcnn/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/mona/computer_vision/py-faster-rcnn',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
Traceback (most recent call last):
  File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 62, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/factory.py", line 38, in get_imdb
    return __sets[name]()
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/factory.py", line 20, in <lambda>
    __sets[name] = (lambda split=split, year=year: pascal_voc(split, year))
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 38, in __init__
    self._image_index = self._load_image_set_index()
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 82, in _load_image_set_index
    'Path does not exist: {}'.format(image_set_file)
AssertionError: Path does not exist: /home/mona/computer_vision/py-faster-rcnn/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt
mona@pascal:~/computer_vision/py-faster-rcnn$ ls
caffe-fast-rcnn  data  experiments  lib  LICENSE  models  README.md  tools  VOCdevkit  VOCdevkit_08-Jun-2007.tar  VOCtest_06-Nov-2007.tar  VOCtrainval_06-Nov-2007.tar
mona@pascal:~/computer_vision/py-faster-rcnn$ ls VOC
VOCdevkit/                   VOCdevkit_08-Jun-2007.tar    VOCtest_06-Nov-2007.tar      VOCtrainval_06-Nov-2007.tar  
mona@pascal:~/computer_vision/py-faster-rcnn$ ls VOCdevkit
create_segmentations_from_detections.m  example_classifier.m  example_layout.m     local    viewanno.m  VOC2007
devkit_doc.pdf                          example_detector.m    example_segmenter.m  results  viewdet.m   VOCcode

```

**Comment by monajalal** [comment]
copied the VOCdevkit to data folder and renamed it to VOCdevkit2007 and have no problem now.

**Comment by JFishLover** [comment]
@monajalal  exactly right
