### ISSUE TITLE
AssertionError: Path does not exist: ...py-faster-rcnn/data/coco/images/train2014/COCO_train2014_000000262145.jpg

### ISSUE THREAD

**Issue by monajalal** [rbgirshick/py-faster-rcnn#376]
So I got the data from mscoco website and created the coco/annotations folder in data but I got the following error. How do you expect to get the data if not from mscoco website? 

```
mona@pascal:~/computer_vision/py-faster-rcnn/data$ mkdir coco
mona@pascal:~/computer_vision/py-faster-rcnn/data$ cd coco
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ mkdir annotations
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ cd annotations/
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ ls
captions_train2014.json  captions_val2014.json  instances_train2014.json  instances_val2014.json  person_keypoints_train2014.json  person_keypoints_val2014.json
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ cd ../../..
mona@pascal:~/computer_vision/py-faster-rcnn$ tools/train_net.py \
>     --gpu 0 \
>     --solver ./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt \
>     --weights data/imagenet_models/VGG16.v2.caffemodel \
>     --imdb coco_2014_train+coco_2014_valminusminival \
>     --iters 490000 \
>     --cfg ./experiments/cfgs/faster_rcnn_end2end.yml
Called with args:
Namespace(cfg_file='./experiments/cfgs/faster_rcnn_end2end.yml', gpu_id=0, imdb_name='coco_2014_train+coco_2014_valminusminival', max_iters=490000, pretrained_model='data/imagenet_models/VGG16.v2.caffemodel', randomize=False, set_cfgs=None, solver='./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt')
Using config:
{'DATA_DIR': '/home/mona/computer_vision/py-faster-rcnn/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/mona/computer_vision/py-faster-rcnn/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/mona/computer_vision/py-faster-rcnn',
 'TEST': {'BBOX_REG': True,mona@pascal:~/computer_vision/py-faster-rcnn/data$ mkdir coco
mona@pascal:~/computer_vision/py-faster-rcnn/data$ cd coco
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ mkdir annotations
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ cd annotations/
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ ls
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ ls
captions_train2014.json  captions_val2014.json  instances_train2014.json  instances_val2014.json  person_keypoints_train2014.json  person_keypoints_val2014.json
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ cd ../../..
mona@pascal:~/computer_vision/py-faster-rcnn$ ls
caffe-fast-rcnn  data  experiments  lib  LICENSE  models  output  README.md  tools  VOCdevkit  VOCdevkit_08-Jun-2007.tar  VOCtest_06-Nov-2007.tar  VOCtrainval_06-Nov-2007.tar
mona@pascal:~/computer_vision/py-faster-rcnn$ tools/train_net.py \
>     --gpu 0 \
>     --solver ./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt \
>     --weights data/imagenet_models/VGG16.v2.caffemodel \
>     --imdb coco_2014_train+coco_2014_valminusminival \
>     --iters 490000 \
>     --cfg ./experiments/cfgs/faster_rcnn_end2end.yml
Called with args:
Namespace(cfg_file='./experiments/cfgs/faster_rcnn_end2end.yml', gpu_id=0, imdb_name='coco_2014_train+coco_2014_valminusminival', max_iters=490000, pretrained_model='data/imagenet_models/VGG16.v2.caffemodel', randomize=False, set_cfgs=None, solver='./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt')
Using config:
{'DATA_DIR': '/home/mona/computer_vision/py-faster-rcnn/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/mona/computer_vision/py-faster-rcnn/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/mona/computer_vision/py-faster-rcnn',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
loading annotations into memory...
Done (t=20.47s)
creating index...
index created!
Loaded dataset `coco_2014_train` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
wrote gt roidb to /home/mona/computer_vision/py-faster-rcnn/data/cache/coco_2014_train_gt_roidb.pkl
done
Preparing training data...
Traceback (most recent call last):
  File "tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/mona/computer_vision/py-famona@pascal:~/computer_vision/py-faster-rcnn/data$ mkdir coco
mona@pascal:~/computer_vision/py-faster-rcnn/data$ cd coco
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ mkdir annotations
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ cd annotations/
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ ls
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ ls
captions_train2014.json  captions_val2014.json  instances_train2014.json  instances_val2014.json  person_keypoints_train2014.json  person_keypoints_val2014.json
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ cd ../../..
mona@pascal:~/computer_vision/py-faster-rcnn$ ls
caffe-fast-rcnn  data  experiments  lib  LICENSE  models  output  README.md  tools  VOCdevkit  VOCdevkit_08-Jun-2007.tar  VOCtest_06-Nov-2007.tar  VOCtrainval_06-Nov-2007.tar
mona@pascal:~/computer_vision/py-faster-rcnn$ tools/train_net.py \
>     --gpu 0 \
>     --solver ./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt \
>     --weights data/imagenet_models/VGG16.v2.caffemodel \
>     --imdb coco_2014_train+coco_2014_valminusminival \
>     --iters 490000 \
>     --cfg ./experiments/cfgs/faster_rcnn_end2end.yml
Called with args:
Namespace(cfg_file='./experiments/cfgs/faster_rcnn_end2end.yml', gpu_id=0, imdb_name='coco_2014_train+coco_2014_valminusminival', max_iters=490000, pretrained_model='data/imagenet_models/VGG16.v2.caffemodel', randomize=False, set_cfgs=None, solver='./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt')
Using config:
{'DATA_DIR': '/home/mona/computer_vision/py-faster-rcnn/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/mona/computer_vision/py-faster-rcnn/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/mona/computer_vision/py-faster-rcnn',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
loading annotations into memory...
Done (t=20.47s)
creating index...
index created!
Loaded dataset `coco_2014_train` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
wrote gt roidb to /home/mona/computer_vision/py-faster-rcnn/data/cache/coco_2014_train_gt_roidb.pkl
done
Preparing training data...
Traceback (most recent call last):
  File "tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "tools/train_net.py", line 69, in commona@pascal:~/computer_vision/py-faster-rcnn/data$ mkdir coco
mona@pascal:~/computer_vision/py-faster-rcnn/data$ cd coco
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ mkdir annotations
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ cd annotations/
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ ls
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ ls
captions_train2014.json  captions_val2014.json  instances_train2014.json  instances_val2014.json  person_keypoints_train2014.json  person_keypoints_val2014.json
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ cd ../../..
mona@pascal:~/computer_vision/py-faster-rcnn$ ls
caffe-fast-rcnn  data  experiments  lib  LICENSE  models  output  README.md  tools  VOCdevkit  VOCdevkit_08-Jun-2007.tar  VOCtest_06-Nov-2007.tar  VOCtrainval_06-Nov-2007.tar
mona@pascal:~/computer_vision/py-faster-rcnn$ tools/train_net.py \
>     --gpu 0 \
>     --solver ./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt \
>     --weights data/imagenet_models/VGG16.v2.caffemodel \
>     --imdb coco_2014_train+coco_2014_valminusminival \
>     --iters 490000 \
>     --cfg ./experiments/cfgs/faster_rcnn_end2end.yml
Called with args:
Namespace(cfg_file='./experiments/cfgs/faster_rcnn_end2end.yml', gpu_id=0, imdb_name='coco_2014_train+coco_2014_valminusminival', max_iters=490000, pretrained_model='data/imagenet_models/VGG16.v2.caffemodel', randomize=False, set_cfgs=None, solver='./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt')
Using config:
{'DATA_DIR': '/home/mona/computer_vision/py-faster-rcnn/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/mona/computer_vision/py-faster-rcnn/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/mona/computer_vision/py-faster-rcnn',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
loading annotations into memory...
Done (t=20.47s)
creating index...mona@pascal:~/computer_vision/py-faster-rcnn/data$ mkdir coco
mona@pascal:~/computer_vision/py-faster-rcnn/data$ cd coco
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ mkdir annotations
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco$ cd annotations/
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ ls
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ ls
captions_train2014.json  captions_val2014.json  instances_train2014.json  instances_val2014.json  person_keypoints_train2014.json  person_keypoints_val2014.json
mona@pascal:~/computer_vision/py-faster-rcnn/data/coco/annotations$ cd ../../..
mona@pascal:~/computer_vision/py-faster-rcnn$ ls
caffe-fast-rcnn  data  experiments  lib  LICENSE  models  output  README.md  tools  VOCdevkit  VOCdevkit_08-Jun-2007.tar  VOCtest_06-Nov-2007.tar  VOCtrainval_06-Nov-2007.tar
mona@pascal:~/computer_vision/py-faster-rcnn$ tools/train_net.py \
>     --gpu 0 \
>     --solver ./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt \
>     --weights data/imagenet_models/VGG16.v2.caffemodel \
>     --imdb coco_2014_train+coco_2014_valminusminival \
>     --iters 490000 \
>     --cfg ./experiments/cfgs/faster_rcnn_end2end.yml
Called with args:
Namespace(cfg_file='./experiments/cfgs/faster_rcnn_end2end.yml', gpu_id=0, imdb_name='coco_2014_train+coco_2014_valminusminival', max_iters=490000, pretrained_model='data/imagenet_models/VGG16.v2.caffemodel', randomize=False, set_cfgs=None, solver='./models/coco/VGG16/faster_rcnn_end2end/solver.prototxt')
Using config:
{'DATA_DIR': '/home/mona/computer_vision/py-faster-rcnn/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/mona/computer_vision/py-faster-rcnn/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/mona/computer_vision/py-faster-rcnn',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
loading annotations into memory...
Done (t=20.47s)
creating index...
index created!
Loaded dataset `coco_2014_train` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
wrote gt roidb to /home/mona/computer_vision/py-faster-rcnn/data/cache/coco_2014_train_gt_roidb.pkl
done
Preparing training data...
Traceback (most recent call last):
  File "tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 122, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/roi_data_layer/roidb.py", line 24, in prepare_roidb
    for i in xrange(imdb.num_images)]
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 107, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 120, in image_path_from_index
    'Path does not exist: {}'.format(image_path)
AssertionError: Path does not exist: /home/mona/computer_vision/py-faster-rcnn/data/coco/images/train2014/COCO_train2014_000000262145.jpg

index created!
Loaded dataset `coco_2014_train` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
wrote gt roidb to /home/mona/computer_vision/py-faster-rcnn/data/cache/coco_2014_train_gt_roidb.pkl
done
Preparing training data...
Traceback (most recent call last):
  File "tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 122, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/roi_data_layer/roidb.py", line 24, in prepare_roidb
    for i in xrange(imdb.num_images)]
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 107, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 120, in image_path_from_index
    'Path does not exist: {}'.format(image_path)
AssertionError: Path does not exist: /home/mona/computer_vision/py-faster-rcnn/data/coco/images/train2014/COCO_train2014_000000262145.jpg
bined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 122, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/roi_data_layer/roidb.py", line 24, in prepare_roidb
    for i in xrange(imdb.num_images)]
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 107, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 120, in image_path_from_index
    'Path does not exist: {}'.format(image_path)
AssertionError: Path does not exist: /home/mona/computer_vision/py-faster-rcnn/data/coco/images/train2014/COCO_train2014_000000262145.jpg
ster-rcnn/tools/../lib/fast_rcnn/train.py", line 122, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/roi_data_layer/roidb.py", line 24, in prepare_roidb
    for i in xrange(imdb.num_images)]
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 107, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 120, in image_path_from_index
    'Path does not exist: {}'.format(image_path)
AssertionError: Path does not exist: /home/mona/computer_vision/py-faster-rcnn/data/coco/images/train2014/COCO_train2014_000000262145.jpg

          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
loading annotations into memory...
Done (t=20.47s)
creating index...
index created!
Loaded dataset `coco_2014_train` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
wrote gt roidb to /home/mona/computer_vision/py-faster-rcnn/data/cache/coco_2014_train_gt_roidb.pkl
done
Preparing training data...
Traceback (most recent call last):
  File "tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 122, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/roi_data_layer/roidb.py", line 24, in prepare_roidb
    for i in xrange(imdb.num_images)]
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 107, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/datasets/coco.py", line 120, in image_path_from_index
    'Path does not exist: {}'.format(image_path)
AssertionError: Path does not exist: /home/mona/computer_vision/py-faster-rcnn/data/coco/images/train2014/COCO_train2014_000000262145.jpg

```

**Comment by rtgoring** [comment]
Are you certain that that path is correct, and that that image with that extension is there?

**Comment by hgaiser** [comment]
As @rtgoring suggested, I'm assuming the file is there but with a PNG extension?

**Comment by rtgoring** [comment]
In coco.py, line 116 ".jpg" is appended to the filename. If your using another extension, you must change the file type.

**Comment by MartinPlantinga** [comment]
I had the same error, and it's because you don't have the dataset under the correct path. Your /path/to/coco/ should contain:
	|- annotations/  
	|- common/  
	|- images/		
	|- license.txt  
	|- LuaAPI/  
	|- MatlabAPI/  
	|- PythonAPI/  
	|- README.txt  
	|- results/

where images contains:
	|- test2014
	|- train2014
	|- val2014
	|- test2015
	|- test2017
	|- train2017
	|- unlabeled2017
	|- val2017
These are the datasets that are downloaded from the cocodataset.org website.

and annotations contains:
	|- captions_train2014.json  
	|- captions_val2017.json
	|- instances_val2014.json           
	|- person_keypoints_train2017.json
	|- captions_train2017.json  
	|- instances_train2014.json  
	|- instances_val2017.json
	|- person_keypoints_val2014.json
	|- captions_val2014.json    
	|- instances_train2017.json  
	|- person_keypoints_train2014.json  
	|_ person_keypoints_val2017.json
