### ISSUE TITLE
IndexError: index 21 is out of bounds for axis 1 with size 21

### ISSUE THREAD

**Issue by monajalal** [rbgirshick/py-faster-rcnn#378]
I get this error:

```
I1021 15:28:28.457094  3644 net.cpp:283] Network initialization done.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 548317115
I1021 15:28:29.808356  3644 net.cpp:816] Ignoring source layer data
I1021 15:28:29.917737  3644 net.cpp:816] Ignoring source layer drop6
I1021 15:28:29.932386  3644 net.cpp:816] Ignoring source layer drop7
I1021 15:28:29.932440  3644 net.cpp:816] Ignoring source layer fc7_drop7_0_split
I1021 15:28:29.932839  3644 net.cpp:816] Ignoring source layer loss_cls
I1021 15:28:29.932855  3644 net.cpp:816] Ignoring source layer loss_bbox
I1021 15:28:29.934864  3644 net.cpp:816] Ignoring source layer silence_rpn_cls_score
I1021 15:28:29.934897  3644 net.cpp:816] Ignoring source layer silence_rpn_bbox_pred


Loaded network /home/mona/computer_vision/py-faster-rcnn/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel
```

Demo for data/demo/little-boy-with-red-umbrella.jpg
0:backpack:0.843390643597
Threshold is :0.5 : backpack
0:tie:0.999452531338
Threshold is :0.5 : tie
Traceback (most recent call last):
  File "./tools/demo.py", line 187, in <module>
    demo(net, im_name)
  File "./tools/demo.py", line 124, in demo
    cls_scores = scores[:, cls_ind]
IndexError: index 21 is out of bounds for axis 1 with size 21

```


For this code (which is slightly modified) where I am using MSCOCO categories. Can you please guide why is this wrong and how to fix it?
```
# !/usr/bin/env python
# --------------------------------------------------------
# Faster R-CNN
# Copyright (c) 2015 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Ross Girshick
# --------------------------------------------------------

"""
Demo script showing detections in sample images.

See README.md for installation instructions before running.
"""

import _init_paths
from fast_rcnn.config import cfg
from fast_rcnn.test import im_detect
from fast_rcnn.nms_wrapper import nms
from utils.timer import Timer
import matplotlib.pyplot as plt
import numpy as np
import scipy.io as sio
import caffe, os, sys, cv2
import argparse
import csv
import glob

'''
CLASSES = ('**background**',
           'aeroplane', 'bicycle', 'bird', 'boat',
           'bottle', 'bus', 'car', 'cat', 'chair',
           'cow', 'diningtable', 'dog', 'horse',
           'motorbike', 'person', 'pottedplant',
           'sheep', 'sofa', 'train', 'tvmonitor')
'''

CLASSES = ('**background**',
         'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 
         'cow', 'elephant', 'bear', 'zebra', 'giraffe', 
         'umbrella', 'handbag', 'backpack', 'tie', 'suitcase', 
         'frisbee', 'skis', 'snowboard', 'sports ball', 'kite',  
         'baseball glove', 'baseball bat', 'skateboard',
         'surfboard', 'tennis racket', 'wine glass', 'cup', 'fork', 
         'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich',
         'orange', 'broccoli', 'carrot', 'hotdog', 'pizza',  'donut',
         'cake', 'chair', 'couch', 'plant', 'dining table','toilet', 
         'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
         'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 
         'clock', 'person', 'scissors', 'teddy bear', 'toothbrush',
         'vase', 'car','motorcycle', 'airplane', 'bus', 'train', 
         'truck', 'traffic light', 'fire hydrant', 'parking meter', 'stop sign')

NETS = {'vgg16': ('VGG16',
                  'VGG16_faster_rcnn_final.caffemodel'),
        'zf': ('ZF',
                  'ZF_faster_rcnn_final.caffemodel')}

def vis_detections(im, class_name, dets, image_name, thresh=0.5):
    """Draw detected bounding boxes."""
    inds = np.where(dets[:, -1] >= thresh)[0]
    if len(inds) == 0:
        return

```
im = im[:, :, (2, 1, 0)]
fig, ax = plt.subplots(figsize=(12, 12))
ax.imshow(im, aspect='equal')
for i in inds:
    bbox = dets[i, :4]
    score = dets[i, -1]

    ax.add_patch(
        plt.Rectangle((bbox[0], bbox[1]),
                      bbox[2] - bbox[0],
                      bbox[3] - bbox[1], fill=False,
                      edgecolor='red', linewidth=3.5)
        )
    ax.text(bbox[0], bbox[1] - 2,
            '{:s} {:.3f}'.format(class_name, score),
            bbox=dict(facecolor='blue', alpha=0.5),
            fontsize=14, color='white')

    print('{0}:{1}:{2}'.format(i, class_name, score))
    image_class_score_file_name = 'image_scores/'+image_name[:-4]+'.csv'
    with open(image_class_score_file_name, 'a') as image_class_score_file:
        csv_writer = csv.writer(image_class_score_file)
        csv_writer.writerow([class_name, score])


ax.set_title(('{} detections with '
              'p({} | box) >= {:.1f}').format(class_name, class_name,
                                              thresh),
              fontsize=14)
print('{0} :{1} : {2}'.format("Threshold is",thresh,class_name))
plt.axis('off')
plt.tight_layout()
plt.draw()
```

def demo(net, image_name):
    """Detect object classes in an image using pre-computed object proposals."""

```
# Load the demo image
im_file = os.path.join(cfg.DATA_DIR, 'demo', image_name)
im = cv2.imread(im_file)

# Detect all object classes and regress object bounds
timer = Timer()
#timer.tic()
scores, boxes = im_detect(net, im)
#timer.toc()
#print ('Detection took {:.3f}s for '
#       '{:d} object proposals').format(timer.total_time, boxes.shape[0])

# Visualize detections for each class
CONF_THRESH = 0.5
NMS_THRESH = 0.3
for cls_ind, cls in enumerate(CLASSES[1:]):
    cls_ind += 1 # because we skipped background
    cls_boxes = boxes[:, 4*cls_ind:4*(cls_ind + 1)]
    cls_scores = scores[:, cls_ind]
    dets = np.hstack((cls_boxes,
                      cls_scores[:, np.newaxis])).astype(np.float32)
    keep = nms(dets, NMS_THRESH)
    dets = dets[keep, :]
    vis_detections(im, cls, dets, image_name, thresh=CONF_THRESH)
```

def parse_args():
    """Parse input arguments."""
    parser = argparse.ArgumentParser(description='Faster R-CNN demo')
    parser.add_argument('--gpu', dest='gpu_id', help='GPU device id to use [0]',
                        default=0, type=int)
    parser.add_argument('--cpu', dest='cpu_mode',
                        help='Use CPU mode (overrides --gpu)',
                        action='store_true')
    parser.add_argument('--net', dest='demo_net', help='Network to use [vgg16]',
                        choices=NETS.keys(), default='vgg16')

```
args = parser.parse_args()

return args
```

if **name** == '**main**':
    cfg.TEST.HAS_RPN = True  # Use RPN for proposals

```
args = parse_args()

prototxt = os.path.join(cfg.MODELS_DIR, NETS[args.demo_net][0],
                        'faster_rcnn_alt_opt', 'faster_rcnn_test.pt')
caffemodel = os.path.join(cfg.DATA_DIR, 'faster_rcnn_models',
                          NETS[args.demo_net][1])

if not os.path.isfile(caffemodel):
    raise IOError(('{:s} not found.\nDid you run ./data/script/'
                   'fetch_faster_rcnn_models.sh?').format(caffemodel))

if args.cpu_mode:
    caffe.set_mode_cpu()
else:
    caffe.set_mode_gpu()
    caffe.set_device(args.gpu_id)
    cfg.GPU_ID = args.gpu_id
net = caffe.Net(prototxt, caffemodel, caffe.TEST)

print '\n\nLoaded network {:s}'.format(caffemodel)

# Warmup on a dummy image
im = 128 * np.ones((300, 500, 3), dtype=np.uint8)
for i in xrange(2):
    _, _= im_detect(net, im)

path = "data/demo/*.jpg"
im_names = []
image_names = glob.glob(path)
for image_instance in image_names:
    head, tail = os.path.split(image_instance)
    im_names.append(tail)

#im_names = ['000456.jpg', '000542.jpg', '001150.jpg',
#            '001763.jpg', '004545.jpg']
for im_name in im_names:
    print '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
    print 'Demo for data/demo/{}'.format(im_name)
    demo(net, im_name)

plt.show()
```

```
The code works with other categories in that are commented 
```

**Comment by rtgoring** [comment]
Looks like you are using 66 classes. Have you modified your prototxt (.pt) files to represent this? You should change the num_classes parameter, and possibly others. I apologize as I have not worked with the alt opt model.

**Comment by monajalal** [comment]
@rtgoring  So does VGG detect classes from mscoco? How can I find the complete class names that VGG detect?
Those 66 categories are from MSCOCO. Also which of these .pt should I modify?

mona@pascal:~/computer_vision/py-faster-rcnn$ find . -name "*.pt" 
```
./models/pascal_voc/ZF/faster_rcnn_alt_opt/stage1_fast_rcnn_solver30k40k.pt
./models/pascal_voc/ZF/faster_rcnn_alt_opt/stage2_fast_rcnn_train.pt
./models/pascal_voc/ZF/faster_rcnn_alt_opt/stage1_rpn_train.pt
./models/pascal_voc/ZF/faster_rcnn_alt_opt/faster_rcnn_test.pt
./models/pascal_voc/ZF/faster_rcnn_alt_opt/rpn_test.pt
./models/pascal_voc/ZF/faster_rcnn_alt_opt/stage1_fast_rcnn_train.pt
./models/pascal_voc/ZF/faster_rcnn_alt_opt/stage2_fast_rcnn_solver30k40k.pt
./models/pascal_voc/ZF/faster_rcnn_alt_opt/stage1_rpn_solver60k80k.pt
./models/pascal_voc/ZF/faster_rcnn_alt_opt/stage2_rpn_train.pt
./models/pascal_voc/ZF/faster_rcnn_alt_opt/stage2_rpn_solver60k80k.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/stage1_fast_rcnn_solver30k40k.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/stage2_fast_rcnn_train.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/stage1_rpn_train.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/faster_rcnn_test.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/rpn_test.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/stage1_fast_rcnn_train.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/stage2_fast_rcnn_solver30k40k.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/stage1_rpn_solver60k80k.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/stage2_rpn_train.pt
./models/pascal_voc/VGG_CNN_M_1024/faster_rcnn_alt_opt/stage2_rpn_solver60k80k.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/stage1_fast_rcnn_solver30k40k.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/stage2_fast_rcnn_train.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/stage1_rpn_train.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/faster_rcnn_test.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/rpn_test.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/stage1_fast_rcnn_train.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/stage2_fast_rcnn_solver30k40k.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/stage1_rpn_solver60k80k.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/stage2_rpn_train.pt
./models/pascal_voc/VGG16/faster_rcnn_alt_opt/stage2_rpn_solver60k80k.pt

```

**Comment by ahagp** [comment]
Do you solve this problem? I get the same error now.
