### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by eonurk** [rbgirshick/py-faster-rcnn#414]
Hello everybody,

I'm trying to create my own dataset on py-faster-rcnn. I got the following error;

Traceback (most recent call last):
  File "./tools/train_net.py", line 106, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 71, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 64, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/home/onur/py-faster-rcnn/tools/../lib/datasets/factory.py", line 48, in get_imdb
    return __sets[name]()
  File "/home/onur/py-faster-rcnn/tools/../lib/datasets/factory.py", line 21, in <lambda>
    __sets[name] = (lambda split=split: datasets.CarData(split, inria_devkit_path))
TypeError: 'module' object is not callable

I changed my factory.py as following; 

data_path = '/home/onur/py-faster-rcnn/data/CarData'
for split in ['cardata_test']:
    name = '{}'.format(split)
    __sets[name] = (lambda split=split: datasets.CarData(split, data_path))

My data are in a subfolder which is called cardata_test inside CarData. Could you please help me?

Thanks

**Comment by eonurk** [comment]
I actually solved the error but now I get the following

Traceback (most recent call last):
  File "./tools/train_net.py", line 15, in <module>
    from datasets import factory
  File "/home/onur/py-faster-rcnn/tools/../lib/datasets/__init__.py", line 44, in <module>
    raise EnvironmentError(msg)
EnvironmentError: MATLAB command 'matlab' not found. Please add 'matlab' to your PATH.

What is matlab? Where should I put it in?

**Comment by ArturoDeza** [comment]
> I changed my factory.py as following;
> 
> data_path = '/home/onur/py-faster-rcnn/data/CarData'
> for split in ['cardata_test']:
> name = '{}'.format(split)
> __sets[name] = (lambda split=split: datasets.CarData(split, data_path))
> 
> My data are in a subfolder which is called cardata_test inside CarData. Could you please help me?

You said you solved, this but how?
