### ISSUE TITLE
make error with cuda-7.5 and cundnn 5.1

### ISSUE THREAD

**Issue by shomedas** [rbgirshick/py-faster-rcnn#455]
while doing "make all" , I get error:

py-faster-rcnn/caffe-fast-rcnn/include/caffe/util/cudnn.hpp(126): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"

Is cuda-7.5 and cudnn v-5.1 combination not supported?

**Comment by CharelCHEN** [comment]
hello,i am meeting this problem as well.could you please tell how to solver it ?thanks!

**Comment by Microos** [comment]
Try this:
 1). 
        cd caffe-fast-rcnn  
        git remote add caffe https://github.com/BVLC/caffe.git  
        git fetch caffe  
        git merge -X theirs caffe/master  

2).
        remove `self_.attr("phase") = static_cast<int>(this->phase_);` from `include/caffe/layers/python_layer.hpp` after merging.

3). (in `caffe-fast-rcnn`)
        - mkdir build && cd build
        - cmake ..
        - make all -j8
        - make pycaffe -j8

**Comment by baristahell** [comment]
@Microos @shomedas 
I encountered the same issue, so i did what you proposed.
It doesn't do anything, sadly, and still fails at the make part with this error. Did one of you manage to prevent this from happening?

**Comment by baristahell** [comment]
Hey there.
I'm trying to train faster-rcnn on a custom dataset with CUDA 7.5, CuDNN 5.1 and had to do this ( @Microos 's post) to be able to do build caffe.

My issue now is that i get an error when i train the net, the solver can't set an attribute:

>I0324 15:41:08.424839  5348 net.cpp:380] input-data -> gt_boxes
>Traceback (most recent call last):
>  File "./tools/train_net.py", line 112, in <module>
>    max_iters=args.max_iters)
>  File "/opt/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 158, in train_net
>    pretrained_model=pretrained_model)
>  File "/opt/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 44, in __init__
>    self.solver = caffe.SGDSolver(solver_prototxt)
>AttributeError: can't set attribute

Did you encounter this error after you patched the cudnnNanPropagation_t bug? I'm worried it's caused by this BVLC Caffe merge.

Thanks.

**Comment by vignesh1905** [comment]
@Microos Solution worked for me.
