### ISSUE TITLE
Undefined symbol when executing the demo

### ISSUE THREAD

**Issue by vpolflie** [rbgirshick/py-faster-rcnn#479]
Getting the following output when trying to execute the demo:
```

Traceback (most recent call last):
  File "./tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/home/vincent/Documents/Kaggle/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/home/vincent/Documents/Kaggle/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/vincent/Documents/Kaggle/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/vincent/Documents/Kaggle/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/../../build/lib/libcaffe.so.1.0.0-rc3: undefined symbol: _ZN2cv8imencodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11_InputArrayERSt6vectorIhSaIhEERKSB_IiSaIiEE
```

Any idea how I can solve this? I'm using CUDA 8.0 and cudnn 5.1 I think. Followed #237 to solve the issues compiling the caffe folder.

**Comment by raditha** [comment]
I have the same issue when i am running the make mattest.Is there fix for this? thanks in advance

**Comment by Lorna-Liu** [comment]
I have the same problem even with "USE_CUDNN := 0"
Hope someone can help, many thanks!

**Comment by ArturoDeza** [comment]
Did you do:
```
$export PYTHONPATH = /RCNN_root/caffe/python:$PYTHONPATH
$export PYTHONPATH = /RCNN_root/caffe/distribute/python:$PYTHONPATH

```
Futher can you import caffe from python?
```
$ python
>> import caffe
```

**Comment by lxtGH** [comment]
@ArturoDeza  Hi I did this but I got this error 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lxt/study/face-py-faster-rcnn/caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/lxt/study/face-py-faster-rcnn/caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/lxt/study/face-py-faster-rcnn/caffe-fast-rcnn/python/caffe/../../build/lib/libcaffe.so.1.0.0-rc3: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev
