### ISSUE TITLE
from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \ ImportError: libboost_system.so.1.61.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by IvyGongoogle** [rbgirshick/py-faster-rcnn#493]
hello, when I run ./tool/demo.py, it shows error:
`
Traceback (most recent call last):
  File "./tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/media/xxx/object-detection/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/media/xxx/object-detection/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/media/xxx/object-detection/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libboost_system.so.1.61.0: cannot open shared object file: No such file or directory

`
but I have installed libboost through 'apt-get install libboost-dev'.

How solve this problem? 
THANK you in advance!

**Comment by onkarganjewar** [comment]
I ran into a similar issue and resolved it by making the caffe, pycaffe modules again. To be specific, I ran all the steps from installation [instructions](https://github.com/rbgirshick/py-faster-rcnn#installation-sufficient-for-the-demo) again. Hope this helps!

**Comment by IvyGongoogle** [comment]
@onkarganjewar it seems to be the cause of boost

**Comment by onkarganjewar** [comment]
Maybe this [issue](https://github.com/Microsoft/malmo/issues/427) can help you. Again, I'm not sure.

**Comment by IvyGongoogle** [comment]
@onkarganjewar I think `sudo apt-get install --no-install-recommends libboost-all-dev` is right.  Thank you!

**Comment by Akansha62** [comment]
" ImportError: libboost_system.so.1.61.0: cannot open shared object file: No such file or directory"
@IvyGongoogle try to run following commands your issue might get solved.

try to check which libboost_system is present in your system using following commands:
locate libboost_system.so
You will get the location and version.

Go to that directory:
Link your version with the lib system wants using follwoing:

sudo ln -s libboost_system.so<ur version> libboost_system.so.1.61.0

It will solve this error.
happy coding

**Comment by SayantiBardhan** [comment]
Hi,

I am running a code on AWS Deep Learning AMI. After doing

    cmake all caffe-rsdnet
    Downloading the data and trained model. Setting caffe_root = '/home/ubuntu/rsdnet/caffe-rsdnet/'
    On running the command, bash test_rsdnet.sh.
    I get the following error:
![rsdnet](https://user-images.githubusercontent.com/40729359/48921805-38495500-eec8-11e8-9087-43546632efca.png)

I tried multiple time to resolve the issue and I also deleted files and re-imported the file and still get same issues. Assistance would be greatly appreciated.
