### ISSUE TITLE
undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by superwj1990** [rbgirshick/py-faster-rcnn#503]
Hi, @rbgirshick when I run the code, I have this problems:
Traceback (most recent call last):
  File "/home/wangjian/code/py-faster-rcnn/lib/rpn/proposal_layer.py", line 8, in <module>
    import caffe
  File "/home/wangjian/code/py-faster-rcnn/caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/wangjian/code/py-faster-rcnn/caffe-fast-rcnn/python/caffe/pycaffe.py", line 11, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct
/home/wangjian/torch/install/bin/luajit: C++ exception
Can you tell me how to fix it, thanks!

**Comment by nh2** [comment]
Hi, I'm a random person from the Internet. This type of error typically happens when either `libpython2.7.so` (or similar depending on the version) is not linked in, or when it is loaded at run time with `dlopen()` but with `RTLD_LOCAL` when `RTLD_GLOBAL` is needed.
