### ISSUE TITLE
how to use evaluate_recall to report recall for different IOU

### ISSUE THREAD

**Issue by smajida** [rbgirshick/py-faster-rcnn#518]
Hi, 

I want to draw a graph similar to the ones in the paper which shows recalls for different IOU threshold. 
It seems evaluate_recall function which is in imdb file is not called in test_net.py function and only imdb.evaluation_detection is called. 

I added imdb.evaluate_recall function below imdb.evaluation_detection, but I am got the following error:
 ```
rote gt roidb to ./data/cache/voc_2007_test_gt_roidb.pkl
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "./tools/../lib/fast_rcnn/test.py", line 297, in test_net
    imdb.evaluate_recall()
  File "./tools/../lib/datasets/imdb.py", line 150, in evaluate_recall
    max_gt_overlaps = self.roidb[i]['gt_overlaps'].toarray().max(axis=1)
  File "./tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "./tools/../lib/datasets/pascal_voc.py", line 132, in selective_search_roidb
    ss_roidb = self._load_selective_search_roidb(gt_roidb)
  File "./tools/../lib/datasets/pascal_voc.py", line 166, in _load_selective_search_roidb
    'Selective search data not found at: {}'.format(filename)
AssertionError: Selective search data not found at: ./data/selective_search_data/voc_2007_test.mat
```

**Comment by mantou22** [comment]
I have the same problem. Have you solved it?
