### ISSUE TITLE
Cuda Lib64 not found for mac os build

### ISSUE THREAD

**Issue by HamdiHamed1992** [rbgirshick/py-faster-rcnn#527]
an error occured while "make" under "lib"folder

Hamdis-MacBook-Pro:lib hamdihamed$ make
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 55, in locate_cuda
    raise EnvironmentError('The CUDA %s path could not be located in %s' % (k, v))
EnvironmentError: The CUDA lib64 path could not be located in /usr/local/cuda/lib64
make: *** [all] Error 1

**Comment by HamdiHamed1992** [comment]
solution is to change the line 55 code in lib/setup.py : 
cudaconfig = {'home':home, 'nvcc':nvcc,
                  'include': pjoin(home, 'include'),
                  'lib64': pjoin(home, 'lib64')}
with : 
cudaconfig = {'home':home, 'nvcc':nvcc,
                  'include': pjoin(home, 'include'),
                  'lib64': pjoin(home, '**lib**')}

**lib** is the cuda directory

**Comment by zakizadeh** [comment]
thats work for me . thanks a lot
