### ISSUE TITLE
ImportError: No module named _caffe on windows 7

### ISSUE THREAD

**Issue by tanmay796** [rbgirshick/py-faster-rcnn#548]
i downloaded caffe-windows and copied python\caffe folder into my site-packages. But after importing the caffe it gives me following error:
Traceback (most recent call last):
  File "C:\Users\ag185211\Desktop\Tanmay\HappyNet-master\opencv_functions.py", line 23, in <module>
    import caffe
  File "C:\Python27\lib\site-packages\caffe\__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "C:\Python27\lib\site-packages\caffe\pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
**ImportError: No module named _caffe**

But in caffe folder there is -caffe.cpp folder. How should I solve this?
Thanks in advance.

**Comment by vabrishami** [comment]
@tanmay796 Follow these steps to solve the problem:

http://www.cnblogs.com/LaplaceAkuir/p/6484500.html

http://www.cnblogs.com/LaplaceAkuir/p/6445189.html

Following these steps will solve your problem.
