### ISSUE TITLE
ImportError: No module named easydict

### ISSUE THREAD

**Issue by hadi-ghnd** [rbgirshick/py-faster-rcnn#562]
Hi,

I'm trying to run the demo of **py-faster-rcnn** with `python ./tools/demo.py --gpu 0 --net vgg16`.
I have done all the previous steps. But now I get this error:

> Traceback (most recent call last):
>   File "./tools/demo.py", line 17, in <module>
>     from fast_rcnn.config import cfg
>   File "/home/hadi/Software/py-faster-rcnn/tools/../lib/fast_rcnn/config.py", line 23, in <module>
>     from easydict import EasyDict as edict
> ImportError: No module named easydict

I have installed easydict with both these commands:

`sudo pip install easydict`
`pip install easydict`

Is this related to python path? I have installed both python 2.7 and 3.5. Since then I get all these python related errors. How can I fix this?

**Comment by onkarganjewar** [comment]
Make sure the python path is correct. For example,
$ echo $PYTHONPATH
/home/student/objectDetection/py-faster-rcnn/caffe-fast-rcnn/python

Note: Notice, the paths are from **py-faster-rcnn** repository itself and not some external directory where you might have downloaded/installed the caffe by yourself. This is one of the mistakes that I did and faced many errors due to it.

**Comment by guiyuliu** [comment]
@onkarganjewar 
hello ， I have installed caffe before ,should I install and make it in "/caffe-fast-rcnn "again ?
what if my PYTHONPATH is /opt/caffe/python ?
looking forward to your answer

**Comment by onkarganjewar** [comment]
@guiyuliu Yes, I do believe you should [make the caffe](https://github.com/rbgirshick/py-faster-rcnn#requirements-software) in the cloned 'caffe-fast-rcnn' repository. Also, make sure that your $PYTHONPATH and $CAFFE_ROOT are correct i.e. set to the path within cloned fast-rcnn repository and not some external directory. For more detailed instructions, give [this](https://github.com/rbgirshick/py-faster-rcnn/issues/427#issuecomment-281213640) comment a try. Hope this helps!
