### ISSUE TITLE
error: "only keep anchors inside the image",  with ImageNet as train datasets.

### ISSUE THREAD

**Issue by leejiajun** [rbgirshick/py-faster-rcnn#63]
i trained with ImageNet, but met an error in /lib/rpn/anchor_target_layer.py.

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 132, in train_rpn
    max_iters=max_iters)
  File "/home/lijiajun/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 136, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/lijiajun/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 104, in train_model
    self.solver.step(1)
  File "/home/lijiajun/py-faster-rcnn/tools/../lib/rpn/anchor_target_layer.py", line 137, in forward
    gt_argmax_overlaps = overlaps.argmax(axis=0)
ValueError: attempt to get argmax of an empty sequence
```
when run at "only keep anchors inside the image", len(ids_inside) is equal to 0.

    # only keep anchors inside the image
    inds_inside = np.where(
        (all_anchors[:, 0] >= -self._allowed_border) &
        (all_anchors[:, 1] >= -self._allowed_border) &
        (all_anchors[:, 2] < im_info[1] + self._allowed_border) &  # width
        (all_anchors[:, 3] < im_info[0] + self._allowed_border)    # height
    )[0]
how to solver?

**Comment by leejiajun** [comment]
imagenet dataset have some unusual size of image and  size of object so that RPN can not generate final anchors.

**Comment by melchior-note** [comment]
@leejiajun  can we modify the python scripts to avoid this problem instead of remove the unusual image?

**Comment by zqdeepbluesky** [comment]
@leejiajun 
hi,I met the same problem,did you fix this problem?can you tell me how to solve it?
thanks so much!!!
