### ISSUE TITLE
test_net.py: IOError: [Errno 2] No such file or directory: '8453.xml'

### ISSUE THREAD

**Issue by annzheng** [rbgirshick/py-faster-rcnn#660]
When I use the test_net.py, I got this problem:

Evaluating detections
Writing 1 VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "F:\faster_rcnn_version\fasterRcnn_final_v1_5\tools\..\lib\fast_rcnn\test.py", line 295, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "F:\faster_rcnn_version\fasterRcnn_final_v1_5\tools\..\lib\datasets\pascal_voc.py", line 318, in evaluate_detections
    self._do_python_eval(output_dir)
  File "F:\faster_rcnn_version\fasterRcnn_final_v1_5\tools\..\lib\datasets\pascal_voc.py", line 281, in _do_python_eval
    use_07_metric=use_07_metric)
  File "F:\faster_rcnn_version\fasterRcnn_final_v1_5\tools\..\lib\datasets\voc_eval.py", line 109, in voc_eval
    recs[imagename] = parse_rec(annopath.format(imagename))
  File "F:\faster_rcnn_version\fasterRcnn_final_v1_5\tools\..\lib\datasets\voc_eval.py", line 14, in parse_rec
    tree = ET.parse(filename)
  File "C:\ProgramData\Anaconda2\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\ProgramData\Anaconda2\lib\xml\etree\ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '8453.xml'

What should I do?

**Comment by jieyongshi** [comment]
Hi~I met the same problem. Have you solved it?

**Comment by trungphan9x** [comment]
I got the same problem also. Have you guys solved it? Thx

**Comment by MartinHHF** [comment]
I got the same problem.. Have you solved it? Thx in advanced.

**Comment by tongjuntx** [comment]
Hi~I met the same problem. Have you solved it?

**Comment by yangtian98** [comment]
I met the same problem. Have you solved it?

**Comment by alsilence** [comment]
I met the same problem.have you solved it ?

**Comment by 1317729246** [comment]
I met the same problem.have you solved it ?

**Comment by 1317729246** [comment]
I have solved the problem. You can refer to [https://blog.csdn.net/w15071453963/article/details/98597404](url)

**Comment by 1317729246** [comment]
I hava solved the problem. you can refer to https://blog.csdn.net/w15071453963/article/details/98597404.

**Comment by ghost** [comment]
> I hava solved the problem. you can refer to https://blog.csdn.net/w15071453963/article/details/98597404.

thank u!I have solve the problem by modify the definition of 'annopath' in /lib/datasets/pascal_voc.py.
