### ISSUE TITLE
Plot 4 loss curves using 'parse_log.py' tool

### ISSUE THREAD

**Issue by flipflop98** [rbgirshick/py-faster-rcnn#69]
Hello every py-faster-rcnn users,

Here I write one error which occurs while running 'parse_log.py' program. Any idea?

Thank you for any comments in advance.

ch723.kim@ubuntu:~/samba/py-faster-rcnn-master$ python ./caffe-fast-rcnn/tools/extra/parse_log.py ./experiments/logs/kitti_faster_rcnn_ZF.txt.2016-01-19_21-32-39 .
Traceback (most recent call last):
  File "./caffe-fast-rcnn/tools/extra/parse_log.py", line 209, in <module>
    main()
  File "./caffe-fast-rcnn/tools/extra/parse_log.py", line 202, in main
    train_dict_list, test_dict_list = parse_log(args.logfile_path)
  File "./caffe-fast-rcnn/tools/extra/parse_log.py", line 50, in parse_log
    start_time = extract_seconds.get_start_time(f, logfile_year)
  File "/home/ch723.kim/samba/py-faster-rcnn-master/caffe-fast-rcnn/tools/extra/extract_seconds.py", line 47, in get_start_time
    start_datetime = extract_datetime_from_line(line, year)
  File "/home/ch723.kim/samba/py-faster-rcnn-master/caffe-fast-rcnn/tools/extra/extract_seconds.py", line 10, in extract_datetime_from_line
    month = int(line[0][1:3])
ValueError: invalid literal for int() with base 10: 'ol'
ch723.kim@ubuntu:~/samba/py-faster-rcnn-master$

**Comment by Sancerio** [comment]
Hi @flipflop98, the parse_log.py contains code that looks for the string "Iteration" for every line and assume that the month (```month = int(line[0][1:3])```) is always embedded in that line. You can verify that this is not the case in the faster-rcnn log file by searching for "Iteration" in it. You can modify the code to only extract_seconds if the line is started with ```something``` since I forgot what the line with loss is started with. Hope this helps!

**Comment by leon-woo** [comment]
I've modified the parse_log.py for faster_rcnn, but only for this project. Hers are my files, https://pan.baidu.com/s/1slaVUzV,  just copy these files to caffe-fast-rcnn/tools/extra/, and cover the original corresponding files.

**Comment by peterWon** [comment]
@leon-woo Hi ,could you please tell me how to generate the log file? I can't find it in my 'tmp' folder. Thanks a lot!

**Comment by leon-woo** [comment]
@peterWon you can use it just as the original version in caffe, but only for 4 step training log:)

**Comment by lolongcovas** [comment]
thanks @leon-woo for sharing new plot. however, the link it seems broken, can u paste the code here? best
