### ISSUE TITLE
Permission denied:  _multiprocessing.SemLock

### ISSUE THREAD

**Issue by xmubingo** [rbgirshick/py-faster-rcnn#7]
--------------log-------
Logging output to experiments/logs/faster_rcnn_alt_opt_VGG16_.txt.2015-10-26_11-22-39
./tools/train_faster_rcnn_alt_opt.py --gpu 2 --net_name VGG16 --weights data/imagenet_models/VGG16.v2.caffemodel --imdb voc_2007_trainval --cfg experiments/cfgs/faster_rcnn_alt_opt.yml
Called with args:
Namespace(cfg_file='experiments/cfgs/faster_rcnn_alt_opt.yml', gpu_id=2, imdb_name='voc_2007_trainval', net_name='VGG16', pretrained_model='data/imagenet_models/VGG16.v2.caffemodel', set_cfgs=None)
Traceback (most recent call last):
  File "./tools/train_faster_rcnn_alt_opt.py", line 224, in <module>
    mp_queue = mp.Queue()
  File "/mark/caffe-soft-bin/anaconda/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/mark/caffe-soft-bin/anaconda/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/mark/caffe-soft-bin/anaconda/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/mark/caffe-soft-bin/anaconda/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied

I found the solution from http://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied,  but I don't have root privilege. So, is there any way to solve this problem?

**Comment by xmubingo** [comment]
mp_queue = mp.Queue()

here, mp_queue was used to receive the result of process, while this line made the trouble. so, i comment out this line and replaced with writing the result of process into disk then reading them in the next process.
