### ISSUE TITLE
Syntax Error when running demo.py

### ISSUE THREAD

**Issue by jyhjinghwang** [rbgirshick/py-faster-rcnn#73]
Hi,
When I tried to run demo.py, the following error occurs.

```
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/n/shokuji/dd/jyh/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/n/shokuji/dd/jyh/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/n/shokuji/dd/jyh/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 107
    return {out: self.blobs[out].data for out in outputs}
                                        ^
SyntaxError: invalid syntax
```

I have no idea what happened. Could anyone give some hint? Thanks a lot!

**Comment by gunpowdergreentea** [comment]
did you figure this out?

**Comment by jyhjinghwang** [comment]
It turns out to be Python version issue.

**Comment by baiyancheng20** [comment]
@jyhjinghwang Hi, I met this problem too. How do you solve this problem? Thank you.

**Comment by ShikharGhimire** [comment]
Any answer? Mine shows the syntax error during 'python train_frcnn.py -o simple -p training_annotation'
