### ISSUE TITLE
Issue with CUDA while make

### ISSUE THREAD

**Issue by DaddyWesker** [rbgirshick/py-faster-rcnn#730]
Hello everyone. 

Following installation guide for windows, i'm trying to "make" folder lib. And here is what i'm getting

python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 46, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
make: *** [Makefile:2: all] Error 1

Tried 3 versions of CUDA (6.5, 8.0, 9.1) but all the same. Windows 10. Does anyone know what to do in such case?

**Comment by MjdMahasneh** [comment]
is there any update on the status of this issue? @DaddyWesker  have you managed to solve this problem? please do share

**Comment by DaddyWesker** [comment]
Unfortunately i havent achieved any progress

**Comment by KaiserLew** [comment]
Hi. Have you solved it?

**Comment by ghost** [comment]
Hi, any update on this issue. I am facing same issue. Thank You. please update.

**Comment by MulongXie** [comment]
I fixed this problem by setting the "CUDAHOME" environment variable and restart my machine.

You can follow part of the below link to set CUDAHOME variable.

https://medium.com/@minhplayer95/how-to-install-tensorflow-with-gpu-support-on-windows-10-with-anaconda-4e80a8beaaf0

**Comment by MulongXie** [comment]
You can also refer to this comment for another common windows issue

https://github.com/rbgirshick/py-faster-rcnn/issues/735#issuecomment-372103143

**Comment by MulongXie** [comment]
You can refer to this comment if you're struggling in windows compilation

https://github.com/rbgirshick/py-faster-rcnn/issues/908#issue-473134976

**Comment by ghost** [comment]
Thank you very much, I will give it a try.
