### ISSUE TITLE
How to retrain from a certain stage

### ISSUE THREAD

**Issue by markbulgakov** [rbgirshick/py-faster-rcnn#766]
Hello everybody 

I have a question: how can i retrain network from a certain stage if i had such mistake:

```
im_detect: 2094/2102 0.115s 0.001s
im_detect: 2095/2102 0.115s 0.001s
im_detect: 2096/2102 0.115s 0.001s
im_detect: 2097/2102 0.115s 0.001s
im_detect: 2098/2102 0.115s 0.001s
im_detect: 2099/2102 0.115s 0.001s
im_detect: 2100/2102 0.115s 0.001s
im_detect: 2101/2102 0.115s 0.001s
im_detect: 2102/2102 0.115s 0.001s
Evaluating detections
Writing nos_text_watermark VOC results file
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "/beegfs/16x/home/markb/py-faster-rcnn_sub/tools/../lib/fast_rcnn/test.py", line 295, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/beegfs/16x/home/markb/py-faster-rcnn_sub/tools/../lib/datasets/pascal_voc.py", line 319, in evaluate_detections
    self._write_voc_results_file(all_boxes)
  File "/beegfs/16x/home/markb/py-faster-rcnn_sub/tools/../lib/datasets/pascal_voc.py", line 246, in _write_voc_results_file
    with open(filename, 'wt') as f:
IOError: [Errno 2] No such file or directory: '/beegfs/16x/home/markb/py-faster-rcnn_sub/data/VOCdevkit2007/results/VOC2007/Main/comp4_a9018e27-c604-4faa-9494-455879bf8f27_det_test_nos_text_watermark.txt'

```

I dont want to train it from the beginning. Is there any opportunities to do that?

**Comment by markbulgakov** [comment]
I have found a dicision:

> ./tools/test_net.py --gpu 0 --def models/pascal_voc/VGG16/faster_rcnn_end2end/test.prototxt --net /beegfs/16x/home/markb/py-faster rcnn_sub/output/faster_rcnn_end2end/voc_2007_trainval/vgg16_faster_rcnn_iter_70000.caffemodel --imdb voc_2007_test --cfg experiments/cfgs/faster_rcnn_end2end.ym

**Comment by Ram-Godavarthi** [comment]
@markbulgakov @rbgirshick 
Did you find the solution for the above problem??
Even i got the same error while testing ..

someone please clarify this.

**Comment by EnJiang** [comment]
at root of this repo, run
mkdir -p ./data/VOCdevkit2007/results/VOC2007/Main/
and solve the problem
