### ISSUE TITLE
/pascal_voc.py", line 66  'Path does not exist: {}'.format(image_path)

### ISSUE THREAD

**Issue by HHEjie123** [rbgirshick/py-faster-rcnn#768]
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "/home/hjadmin/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 256, in test_net
    im = cv2.imread(imdb.image_path_at(i))
  File "/home/hjadmin/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 57, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/home/hjadmin/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 66, in image_path_from_index
    'Path does not exist: {}'.format(image_path)
AssertionError: Path does not exist: /home/hjadmin/py-faster-rcnn/data/VOCdevkit2007/VOC2007/JPEGImages/.jpg
how can i solve the problem ,i can guarantee  the path is true

**Comment by pscheich** [comment]
do you have an empty line in your train,test or trainval.txt file?

**Comment by HHEjie123** [comment]
@pscheich,yes,you are right,is I have a empty line,thankyou
