### ISSUE TITLE
ImportError, undefined symbol

### ISSUE THREAD

**Issue by andreasmoegelmose** [rbgirshick/py-faster-rcnn#79]
Hi,

I'm trying to install and run py-faster-rcnn, but run into trouble when importing caffe to Python. I'm not 100% sure this is a bug (as opposed to me doing something stupid), so in that case sorry in advance :-) It does, however, seem to have to do with the build order.

Basically, when I try to run demo.py (or any other example file), I get this error:
``ImportError: /home/huaminren/bin/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/_caffe.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE``

What's interesting, though, is that the symbol is actually defined - grep finds it just fine:
``(caffe)huaminren@AAU99375:~/bin/py-faster-rcnn/caffe-fast-rcnn/python/caffe$ nm -g _caffe.so | grep _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE``
Results in:
``                 U _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE``

Research shows me that this error may originate from the order supplied when linking during the compilation stage, but as the order is supplied by the Makefile I'm guessing that should work. I have no errors when building. I'm running it all in a conda-environment, but I don't think that would cause this problem.

Is it just me doing something wrong?

Best regards,
Andreas Møgelmose

**Comment by leejiajun** [comment]
you cloud try not to use template function or template class.

**Comment by sunshine-zkf** [comment]
Hi，i have the same problem, do you have solved this problem? Thank you very much.
`Traceback (most recent call last):
  File "./tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/home/sunshine_zkf/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/home/sunshine_zkf/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/sunshine_zkf/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/sunshine_zkf/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/_caffe.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE `

**Comment by andreasmoegelmose** [comment]
I'm sorry, it was two years ago and I don't recall if I solved it or found a workaround.
