### ISSUE TITLE
Training Problem on new dataset

### ISSUE THREAD

**Issue by seawei1993** [rbgirshick/py-faster-rcnn#792]
I would like to train a fast-rcnn model on my dataset .
I have generate selective search proposals successfully.
However, the code stops with the error of 
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 189, in train_fast_rcnn
    roidb, imdb = get_roidb(imdb_name, rpn_file=rpn_file)
  File "./tools/train_faster_rcnn_alt_opt.py", line 67, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/mipl/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 118, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/mipl/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 106, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/mipl/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "/home/mipl/py-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 142, in rpn_roidb
    roidb = imdb.merge_roidbs(gt_roidb, rpn_roidb)
  File "/home/mipl/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 246, in merge_roidbs
    b[i]['gt_overlaps']])
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/construct.py", line 454, in vstack
    return bmat([[b] for b in blocks], format=format, dtype=dtype)
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/construct.py", line 533, in bmat
    raise ValueError('blocks[%d,:] is all None
How can I solve this problem? I appreciate it if someone could help.

**Comment by zchrissirhcz** [comment]
I think you should check your annotated file's contents, or their path specified in related code files.
