### ISSUE TITLE
Error about train py-faster-rcnn with end2end.

### ISSUE THREAD

**Issue by crazyLeeab** [rbgirshick/py-faster-rcnn#807]
Beacause some matter about numpy version,I changed the type into int and when I modified the code that "fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image.astype(np.int)#modify",then the error was appeared.  Please give me suggestion,thx a lot.

I0416 21:20:02.793213  5832 layer_factory.cpp:58] Creating layer roi-data
  File "D:\py-faster-rcnn\tools\..\lib\rpn\proposal_target_layer.py", line 69
    labels, rois, bbox_targets, bbox_inside_weights = _sample_rois(all_rois, gt_boxes, fg_rois_per_image,rois_per_image, self._num_classes)
         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "./tools\train_net.py", line 115, in <module>
    max_iters=args.max_iters)
  File "D:\py-faster-rcnn\tools\..\lib\fast_rcnn\train.py", line 160, in train_net
    pretrained_model=pretrained_model)
  File "D:\py-faster-rcnn\tools\..\lib\fast_rcnn\train.py", line 46, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
SystemError: NULL result without error in PyObject_Call

**Comment by HilmiK** [comment]
could you solve the problem ?

**Comment by Leebanana** [comment]
I met the same problem，do you have fixed it?
