### ISSUE TITLE
'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by MulinYu** [rbgirshick/py-faster-rcnn#815]
runfile('G:/法国第二年下/stage/Faster-RCNN-TensorFlow-Python3.5/train.py', wdir='G:/法国第二年下/stage/Faster-RCNN-TensorFlow-Python3.5')
WARNING:tensorflow:From C:\ProgramData\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from G:\法国第二年下\stage\Faster-RCNN-TensorFlow-Python3.5\data\cache\voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
C:\ProgramData\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading initial model weights from ./data/imagenet_weights/vgg16.ckpt
Variables restored: vgg_16/conv1/conv1_1/biases:0
Variables restored: vgg_16/conv1/conv1_2/weights:0
Variables restored: vgg_16/conv1/conv1_2/biases:0
Variables restored: vgg_16/conv2/conv2_1/weights:0
Variables restored: vgg_16/conv2/conv2_1/biases:0
Variables restored: vgg_16/conv2/conv2_2/weights:0
Variables restored: vgg_16/conv2/conv2_2/biases:0
Variables restored: vgg_16/conv3/conv3_1/weights:0
Variables restored: vgg_16/conv3/conv3_1/biases:0
Variables restored: vgg_16/conv3/conv3_2/weights:0
Variables restored: vgg_16/conv3/conv3_2/biases:0
Variables restored: vgg_16/conv3/conv3_3/weights:0
Variables restored: vgg_16/conv3/conv3_3/biases:0
Variables restored: vgg_16/conv4/conv4_1/weights:0
Variables restored: vgg_16/conv4/conv4_1/biases:0
Variables restored: vgg_16/conv4/conv4_2/weights:0
Variables restored: vgg_16/conv4/conv4_2/biases:0
Variables restored: vgg_16/conv4/conv4_3/weights:0
Variables restored: vgg_16/conv4/conv4_3/biases:0
Variables restored: vgg_16/conv5/conv5_1/weights:0
Variables restored: vgg_16/conv5/conv5_1/biases:0
Variables restored: vgg_16/conv5/conv5_2/weights:0
Variables restored: vgg_16/conv5/conv5_2/biases:0
Variables restored: vgg_16/conv5/conv5_3/weights:0
Variables restored: vgg_16/conv5/conv5_3/biases:0
Variables restored: vgg_16/fc6/biases:0
Variables restored: vgg_16/fc7/biases:0
INFO:tensorflow:Restoring parameters from ./data/imagenet_weights/vgg16.ckpt
Loaded.
Fix VGG16 layers..
INFO:tensorflow:Restoring parameters from ./data/imagenet_weights/vgg16.ckpt
Fixed.
Traceback (most recent call last):

  File "<ipython-input-1-313faeab8ddf>", line 1, in <module>
    runfile('G:/法国第二年下/stage/Faster-RCNN-TensorFlow-Python3.5/train.py', wdir='G:/法国第二年下/stage/Faster-RCNN-TensorFlow-Python3.5')

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "G:/法国第二年下/stage/Faster-RCNN-TensorFlow-Python3.5/train.py", line 210, in <module>
    train.train()

  File "G:/法国第二年下/stage/Faster-RCNN-TensorFlow-Python3.5/train.py", line 148, in train
    blobs = self.data_layer.forward()

  File "G:\法国第二年下\stage\Faster-RCNN-TensorFlow-Python3.5\lib\layer_utils\roi_data_layer.py", line 75, in forward
    blobs = self._get_next_minibatch()

  File "G:\法国第二年下\stage\Faster-RCNN-TensorFlow-Python3.5\lib\layer_utils\roi_data_layer.py", line 71, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)

  File "G:\法国第二年下\stage\Faster-RCNN-TensorFlow-Python3.5\lib\utils\minibatch.py", line 30, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb, random_scale_inds)

  File "G:\法国第二年下\stage\Faster-RCNN-TensorFlow-Python3.5\lib\utils\minibatch.py", line 67, in _get_image_blob
    im, im_scale = prep_im_for_blob(im, cfg.FLAGS2["pixel_means"], target_size, cfg.FLAGS.max_size)

  File "G:\法国第二年下\stage\Faster-RCNN-TensorFlow-Python3.5\lib\utils\blob.py", line 35, in prep_im_for_blob
    im = im.astype(np.float32, copy=False)

AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by JingLiJJ** [comment]
你好。这个问题解决了嘛？我也遇到这个了

**Comment by xiaozhang8tuo** [comment]
> 你好。这个问题解决了嘛？我也遇到这个了

你好。这个问题解决了嘛？我又又遇到这个了2333

**Comment by SuperLee188** [comment]
这个问题可以试下把你"G:\法国第二年下\stage\Faster-RCNN-TensorFlow-Python3.5\lib\utils\minibatch.py‘,这个路径中的中文给去掉

**Comment by 540ul4rm6** [comment]
It's because of the name!
http://tn00343140a.pixnet.net/blog/post/303187670-Faster%20RCNN%E9%81%87%E5%88%B0AttributeError:%20'NoneType'%20object%20has%20no%20attribute%20'astype'
