### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by chenxu93** [rbgirshick/py-faster-rcnn#851]
hello can anyone have this problem during training?I don't know how to solve this problem,it cost my too much time!! 

**Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/jin/chenxu/security/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/jin/chenxu/security/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 108, in train_model
    model_paths.append(self.snapshot())
  File "/home/jin/chenxu/security/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 73, in snapshot
    self.bbox_stds[:, np.newaxis])
ValueError: operands could not be broadcast together with shapes (84,1024) (8,1)**

![image](https://user-images.githubusercontent.com/42310082/44338261-fddab100-a4af-11e8-9a2f-1b5300acf8c6.png)
I have chaged the relative parameters in the VGG16 Train.prototxt.
Line 530：
        num_classes:”2‘’
Line 620：
        num_output :“2” 
Line 643：
        num_output: “8”
because I only have one class to traing .
I   have also removed the cache pkl fiies!!!
And I have change the relativce path to absolute path in the *_solver*.py scripts，BUT all of the solution can not work for me.  
How to solve this problem,can someong help me????? 
Thank you in advance！！！

**Comment by saudpp** [comment]
did you solve it?? i have same problem
