### ISSUE TITLE
Solution to the error BB = BB[sorted_ind, :] IndexError: too many indices for array error from voc_eval function

### ISSUE THREAD

**Issue by pavanteja295** [rbgirshick/py-faster-rcnn#855]
I have seen a lot of posts regarding the error  **BB = BB[sorted_ind, :] IndexError: too many indices for array** which i as well encountered while running the evaluation on a very weakly trained model. I actually found a bug in the file pascal_voc.py which causes this issue. 
The **all_boxes** parameter for  the py-faster-rcnn/lib/datasets/pascal_voc.py/evaluate_detection() function in pascal_voc.py is a list of numpy arrays. But in  pascal_voc.py/_write_voc_results_file(all_boxes) function in **line 251** we check if the

>  dets == []
but here **dets**  is of type **<class 'numpy.ndarray'>**  and the statement in **line 251** evaluates to False leading to consider the empty array being written into the output detection file. 

This file with some empty arrays when read in py-faster-rcnn/lib/datasets/eval_voc.py/voc_eval() in **line 148** throws and error as BB is just an array. 

Solution :  In pascal_voc.py/_write_voc_results_file(all_boxes) edit to  **line 251** should be

> dets.tolist()  == []

This wont throw the error any more !

Kudos !

**Comment by atinesh** [comment]
Hello `pavanteja295`, I am trying to train `Faster RCNN`. After resolving so many errors, Now I am stuck with the error you mentioned. I tried making changes as you suggested but it didn't work for me. Here is the detailed error message.

```
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "/home/atinesh/Desktop/FRCNN_ROOT/tools/../lib/fast_rcnn/test.py", line 295, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/atinesh/Desktop/FRCNN_ROOT/tools/../lib/datasets/pascal_voc.py", line 322, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/atinesh/Desktop/FRCNN_ROOT/tools/../lib/datasets/pascal_voc.py", line 285, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/atinesh/Desktop/FRCNN_ROOT/tools/../lib/datasets/voc_eval.py", line 148, in voc_eval
    BB = BB[sorted_ind, :]
IndexError: too many indices for array
```

**Comment by atinesh** [comment]
Hello pavanteja295,
The changes you suggested didn't resolve my problem, But it got resolved by increasing the number of iterations from 70 to 1000 in `./experiments/scripts/faster_rcnn_end2end.sh` (as suggested here [issue 338](https://github.com/rbgirshick/py-faster-rcnn/issues/338)). As I was facing lots of error, I have reduced iterations from 70000 (`default`) to 70.
