### ISSUE TITLE
No such file or directory: '**.xml'

### ISSUE THREAD

**Issue by MartinHHF** [rbgirshick/py-faster-rcnn#862]
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "G:\huafeng\py-faster-rcnn\tools\..\lib\fast_rcnn\test.py", line 295, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "G:\huafeng\py-faster-rcnn\tools\..\lib\datasets\pascal_voc.py", line 317, in evaluate_detections
    self._do_python_eval(output_dir)
  File "G:\huafeng\py-faster-rcnn\tools\..\lib\datasets\pascal_voc.py", line 280, in _do_python_eval
    use_07_metric=use_07_metric)
  File "G:\huafeng\py-faster-rcnn\tools\..\lib\datasets\voc_eval.py", line 109, in voc_eval
    recs[imagename] = parse_rec(annopath.format(imagename))
  File "G:\huafeng\py-faster-rcnn\tools\..\lib\datasets\voc_eval.py", line 14, in parse_rec
    tree = ET.parse(filename)
  File "G:\huafeng\Anaconda2\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "G:\huafeng\Anaconda2\lib\xml\etree\ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'B_3003_1.RIGHT_MLO-resize.xml'

Does anyone has some ideas?

**Comment by tongjuntx** [comment]
i got the same question,have you solved?
