### ISSUE TITLE
No module named 'nms.gpu_nms'`

### ISSUE THREAD

**Issue by rmxhhh** [rbgirshick/py-faster-rcnn#878]
@rbgirshick  Hi,when i run the demo.py on windows,there was an erro shows:
`Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "D:\py-faster-rcnn-master\tools\..\lib\fast_rcnn\test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "D:\py-faster-rcnn-master\tools\..\lib\fast_rcnn\nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named 'nms.gpu_nms'`
I have run setup.py and setup_cuda.py successfully.Can you tell me what's wrong with me?Thank you very much.

**Comment by future8421** [comment]
Hi，have you solved it, How did you do that?
