### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hanlaoshi** [rbgirshick/py-faster-rcnn#891]
Traceback (most recent call last):
File "./tools/trainval_net.py", line 139, in 
max_iters=args.max_iters)
File "/root/TensorFlow-Model/tf-faster-rcnn-master/tools/../lib/model/train_val.py", line 377, in train_net
sw.train_model(sess, max_iters)
File "/root/TensorFlow-Model/tf-faster-rcnn-master/tools/../lib/model/train_val.py", line 278, in train_model
blobs = self.data_layer.forward()
File "/root/TensorFlow-Model/tf-faster-rcnn-master/tools/../lib/roi_data_layer/layer.py", line 87, in forward
blobs = self._get_next_minibatch()
File "/root/TensorFlow-Model/tf-faster-rcnn-master/tools/../lib/roi_data_layer/layer.py", line 83, in _get_next_minibatch
return get_minibatch(minibatch_db, self._num_classes)
File "/root/TensorFlow-Model/tf-faster-rcnn-master/tools/../lib/roi_data_layer/minibatch.py", line 30, in get_minibatch
im_blob, im_scales = _get_image_blob(roidb, random_scale_inds)
File "/root/TensorFlow-Model/tf-faster-rcnn-master/tools/../lib/roi_data_layer/minibatch.py", line 64, in _get_image_blob
im = im[:, ::-1, :]
TypeError: 'NoneType' object is not subscriptable

Anyone can give me some suggestions? Thanks for your help in advance.

**Comment by hongyanghu** [comment]
did you solve it?can you give me some advice?
