### ISSUE TITLE
Successfully Built on Windows 

### ISSUE THREAD

**Issue by MulongXie** [rbgirshick/py-faster-rcnn#908]
For anyone who is struggling in using this repo on windows, download the below repo and replace the lib file.

https://github.com/MrGF/py-faster-rcnn-windows

**Comment by MulongXie** [comment]
There would be an error saying 

**Traceback (most recent call last):                                                 File "setup.py", line 66, in                                               CUDA = locate_cuda()                                                           File "setup.py", line 61, in locate_cuda                                           for k, v in cudaconfig.iteritems():                                          AttributeError: 'dict' object has no attribute 'iteritems'                       make: *** [Makefile:2: all] Error 1
--**

Then you should revise the line 61 `for k, v in cudaconfig.iteritems():` to `for k, v in cudaconfig.items():`
