### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by muhammad-hassan-shakeel** [rbgirshick/py-faster-rcnn#920]
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 52, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDA_PATH
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by zhijianglu** [comment]
i met same problem ，have you deal with it？

**Comment by muhammad-hassan-shakeel** [comment]
Yes, I removed "locate_cuda" line
