### ISSUE TITLE
How do I pass my own object proposals to demo.py

### ISSUE THREAD

**Issue by jainanshul** [rbgirshick/py-faster-rcnn#94]
I am using dlib selective search to generate my object proposal and passing it to im_detect function like below

```
obj_proposals = run_dlib_selective_search(im_file)
im_detect(net, im, obj_proposals)
```

However I see that demo.py ignored the object proposal I provided and created its own based on the configuration settings in config.py. How do I force it to use my own object proposals?

**Comment by jainanshul** [comment]
Figured out that demo.py was hardocoding the cfg.TEST.HAS_RPN = True. However after setting in to false I am getting the error below.

```
Traceback (most recent call last):
  File "./tools/demo_roi.py", line 161, in <module>
    _, _= im_detect(net, im)
  File "/home/ubuntu/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 121, in im_detect
    blobs, im_scales = _get_blobs(im, boxes)
  File "/home/ubuntu/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 105, in _get_blobs
    blobs['rois'] = _get_rois_blob(rois, im_scale_factors)
  File "/home/ubuntu/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 68, in _get_rois_blob
    rois, levels = _project_im_rois(im_rois, im_scale_factors)
  File "/home/ubuntu/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 83, in _project_im_rois
    im_rois = im_rois.astype(np.float, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'
```

**Comment by jainanshul** [comment]
Solved it by using the models/pascal_voc/VGG16/fast_rcnn/test.prototxt instead and removing the following lines from the demo.py

```
# Warmup on a dummy image
    im = 128 * np.ones((300, 500, 3), dtype=np.uint8)
    for i in xrange(2):
        _, _= im_detect(net, im)
```

**Comment by harjatinsingh** [comment]
@jainanshul  can you please share the entire modified demo file ?
