### ISSUE TITLE
improperly commited intermediate build files including pycocotools/_mask.c ?

### ISSUE THREAD

**Issue by moskewcz** [rbgirshick/py-faster-rcnn#99]
i'm not too familiar with the Cython build process or whatever is going on in the pycocotools directory, but this file:
https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/pycocotools/_mask.c

along with the other _ files, seem like intermediate generated files that should not be committed. in any event my first build gave an error at runtime:
````
Traceback (most recent call last):
  File "./tools/train_net.py", line 15, in <module>
    from datasets.factory import get_imdb
  File "/nscratch/forresti/faster_rcnn/py-faster-rcnn/tools/../lib/datasets/factory.py", line 13, in <module>
    from datasets.coco import coco
  File "/nscratch/forresti/faster_rcnn/py-faster-rcnn/tools/../lib/datasets/coco.py", line 20, in <module>
    from pycocotools.coco import COCO
  File "/nscratch/forresti/faster_rcnn/py-faster-rcnn/tools/../lib/pycocotools/coco.py", line 58, in <module>
    import mask
  File "/nscratch/forresti/faster_rcnn/py-faster-rcnn/tools/../lib/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "__init__.pxd", line 155, in init pycocotools._mask (pycocotools/_mask.c:9754)
ValueError: numpy.dtype has the wrong size, try recompiling
````

until i force-recompiled pycocotools; i'm guessing that was due to this issue.

**Comment by rbgirshick** [comment]
Thanks for spotting this. I've removed `_mask.c` and `_mask.so`.
